neo4j/graphql

packages/graphql/tests/integration/advanced-filtering.int.test.ts

Fixes broken test adding env flag.

test: add NEO4J_GRAPHQL_ENABLE_REGEX flag to broken test

---

docs/asciidoc/auth/auth.adoc
packages/graphql/src/schema/make-augmented-schema.test.ts
packages/graphql/src/schema/make-augmented-schema.ts

The typeDefs validation was causing too many issues and after @darrellwarde and I spent some time debugging we realised it would be detrimental to include it! This pr comments out the typedef validation :O. Removing the validation has no effect on the usability of the library and the only side effect would be users get a lesser defined error when they give us some invalid typeDefs.

fix: temporarily disable validateTypeDefs 

---

packages/graphql/src/translate/create-where-and-params.ts
packages/graphql/tests/integration/issues/#190.int.test.ts
packages/graphql/tests/tck/tck-test-files/cypher/advanced-filtering.md
packages/graphql/tests/tck/tck-test-files/cypher/issues/#190.md

Fixes Cypher generation when checking for equality of fields on related nodes, replacing `ALL` with `ANY` to return expected results. See linked issue for example.
`ALL` still used for `_IN` and `_NOT_IN` filters, which _I believe_ is the correct behaviour.
#190 

Replace ALL with ANY in whilst querying relationship equality

---

.eslintrc.js
.prettierrc
package.json
yarn.lock

Switch eslint-plugin-prettier for eslint-config-prettier, this is recommended by Prettier, and the plugin was slowing linting right down. 

Incredibly slow linting

---

packages/graphql/src/classes/Neo4jGraphQL.ts
packages/graphql/src/schema/scalars/Int.ts
packages/graphql/src/schema/scalars/index.ts
packages/graphql/src/utils/get-neo4j-resolve-tree.ts
packages/graphql/tests/tck/tck.test.ts

Remove the parse function of the Int scalar, and instead modify the resolve tree used to generate Cypher, replacing any integer values with Neo4j Integer values, which are checked against the schema to ensure they are of the correct type. 
- #208 
- #186 
- #167 

Fix integer input parsing

---

examples/neo-push/server/package.json

Minor update to the neo-push demo's start script to explicitly call the local `ts-node` when using `nodemon`
When attempting to run the neo-push demo for the first time after setup, I encountered an error within the runtime logs showing that `ts-node` could not be found. 
This was because the `start` script in neo-push-server's package.json used nodemon to execute the ts-node process, but had not set the `--exec` flag to a relative/absolute path, meaning nodemon was implicitly expecting to find the provided argument on a user's $PATH (and I did not have a global ts-node installed). Since ts-node is a dev dependency, the script should be using the locally installed version.
Note: There's a subtle difference in the `test` script, which also calls ts-node without a relative path, because the …

Update neo-push-server to enforce nodemon uses local ts-node install

---

README.md
packages/graphql/README.md
packages/graphql/src/schema/get-relationship-field-meta.test.ts
packages/graphql/src/schema/get-where-fields.ts
packages/graphql/src/schema/make-augmented-schema.ts
packages/graphql/src/translate/connection/create-connection-and-params.test.ts
packages/graphql/src/translate/connection/create-connection-and-params.ts
packages/graphql/src/translate/create-delete-and-params.ts
packages/graphql/src/translate/create-set-relationship-properties-and-params.ts
packages/graphql/src/translate/create-set-relationship-properties.ts
packages/graphql/src/translate/projection/elements/create-datetime-element.test.ts
packages/graphql/src/translate/projection/elements/create-datetime-element.ts
packages/graphql/src/translate/projection/elements/create-point-element.test.ts
packages/graphql/src/translate/projection/elements/create-point-element.ts
packages/graphql/src/translate/projection/elements/create-relationship-property-element.test.ts
packages/graphql/src/translate/projection/elements/create-relationship-property-element.ts
packages/graphql/src/translate/translate-update.ts
packages/graphql/src/translate/where/create-connection-where-and-params.ts
packages/graphql/src/translate/where/create-filter.test.ts
packages/graphql/src/translate/where/create-filter.ts
packages/graphql/src/translate/where/create-node-where-and-params.ts
packages/graphql/src/translate/where/create-relationship-where-and-params.ts
packages/ogm/README.md

Copyright headers, removed comment blocks, changed documentation links.
#192 

General 2.0.0 housekeeping

---

packages/ogm/src/classes/OGM.test.ts
packages/ogm/src/classes/OGM.ts
packages/ogm/tests/integration/ogm.int.test.ts

Remove neoSchema from OGM properties to reduce the chances of someone using it incorrectly. 
https://github.com/neo4j/graphql/issues/188

refactor: remove neoSchema from OGM properties

---

docs/asciidoc/type-definitions/cypher.adoc
packages/graphql/src/schema/resolvers/cypher.ts
packages/graphql/src/translate/create-projection-and-params.ts
packages/graphql/tests/integration/cypher-params.int.test.ts

Adds the ability to inject `cypherParams` into custom cypher queries. 
https://github.com/neo4j/graphql/issues/185

feat: add cypherParams

---

packages/graphql/src/schema/make-augmented-schema.test.ts
packages/graphql/src/schema/resolvers/read.test.ts
packages/graphql/src/schema/resolvers/read.ts
packages/graphql/tests/tck/tck-test-files/schema/arrays.md
packages/graphql/tests/tck/tck-test-files/schema/comments.md
packages/graphql/tests/tck/tck-test-files/schema/custom-mutations.md
packages/graphql/tests/tck/tck-test-files/schema/directive-preserve.md
packages/graphql/tests/tck/tck-test-files/schema/directives/access-directives.md
packages/graphql/tests/tck/tck-test-files/schema/directives/autogenerate.md
packages/graphql/tests/tck/tck-test-files/schema/directives/cypher.md
packages/graphql/tests/tck/tck-test-files/schema/directives/default.md
packages/graphql/tests/tck/tck-test-files/schema/directives/exclude.md
packages/graphql/tests/tck/tck-test-files/schema/directives/ignore.md
packages/graphql/tests/tck/tck-test-files/schema/directives/private.md
packages/graphql/tests/tck/tck-test-files/schema/directives/timestamps.md
packages/graphql/tests/tck/tck-test-files/schema/enum.md
packages/graphql/tests/tck/tck-test-files/schema/extend.md
packages/graphql/tests/tck/tck-test-files/schema/inputs.md
packages/graphql/tests/tck/tck-test-files/schema/interfaces.md
packages/graphql/tests/tck/tck-test-files/schema/issues/#162.md
packages/graphql/tests/tck/tck-test-files/schema/issues/#200.md
packages/graphql/tests/tck/tck-test-files/schema/null.md
packages/graphql/tests/tck/tck-test-files/schema/relationship.md
packages/graphql/tests/tck/tck-test-files/schema/scalar.md
packages/graphql/tests/tck/tck-test-files/schema/simple.md
packages/graphql/tests/tck/tck-test-files/schema/types/bigint.md
packages/graphql/tests/tck/tck-test-files/schema/types/datetime.md
packages/graphql/tests/tck/tck-test-files/schema/types/points.md
packages/graphql/tests/tck/tck-test-files/schema/unions.md

Query return type was previously `[Type]!`, now `[Type!]!` as it should be.
Raised on Discord and tracked in Trello.

Fixed nullability of Query return type

---

docs/asciidoc/guides/migration-guide/queries.adoc

This changes the return type of the autogenerated queries to non-nullable lists of non-nullable types. 

Update documentation regarding query return types

---

packages/graphql/src/schema/make-augmented-schema.ts

Partial fix for #207 . Prevents non null union resolvers from being overwritten with a __resolveType.

Prevent non null union resolvers from being overwritten.

---

packages/graphql/src/auth/get-jwt.ts

prevent app crash with errors `Cannot read property 'token' of undefined`
1. start the neo-push server
`yarn workspace neo-push-server start`
2. query anything
it triggers an error `Cannot read property 'token' of undefined`
it should run smoothly

Fix optional cookie

---

.gitignore
packages/graphql/src/environment.ts
packages/graphql/src/tsconfig.build.json
packages/graphql/src/tsconfig.json
packages/graphql/src/utils/execute.test.ts
packages/graphql/src/utils/execute.ts
packages/graphql/tests/tsconfig.json
packages/graphql/tsconfig.json
tsconfig.base.json

Uses `package.json` to grab the version and package name vs using the environment variable. Changes to ts-config can be explained here: https://stackoverflow.com/a/61467483/10687857

fix: use package json for useragent name and version

---

.github/CODEOWNERS

Removes code owners so team members don't get spam on holidays. As the team grows I would say this is unnecessary for Darrell and me to **both** review everything going in.

config: remove codeowners

---

examples/neo-push/client/src/components/SignIn.tsx
examples/neo-push/client/src/components/SignUp.tsx

enhanced a little bit sign-in and sign-up modals ui in the neo-push example
The link between sign in and sign up modals was made by a secondary button placed just next to the submit button and was prone to confusion.

fix(example/login): avoid confusion caused by secondary button

---

packages/graphql/src/translate/create-auth-and-params.test.ts
packages/graphql/src/translate/create-auth-and-params.ts

Avoid `createAuthPredicate` to lose params when no values attached to them.
In the case of a non authed request for example `$jwt.sub` return undefined.
To fix this I just check `paramValue` before setting it to the `params` object, if it's `undefined` set it to `null`.
Fix: https://github.com/neo4j/graphql/issues/280

fix: losing params while creating Auth Predicate

---

docs/asciidoc/type-definitions/cypher.adoc

A small section in documentation to highlight that double quotes need to be double escaped.
#227 

Mention double escaping for @cypher directive

---

packages/graphql/src/schema/resolvers/cypher.ts
packages/graphql/tests/integration/cypher.int.test.ts
packages/graphql/tests/integration/issues/#315.int.test.ts

The recent changes to custom Cypher made it so that `expectMultipleReturns` of `apoc.cypher.runFirstColumn` is only set to `true` if a node match was found for the return type. Union return types did not meet this requirement, so `expectMultipleReturns` was set to `false` and only 1 record would ever be returned.
It should be clarified that Union returns for custom Cypher will not have relationships automatically projected, and this will only change when we work on querying Unions/Interfaces from the root Query type.
#315 

Custom Cypher and Union return type - preserve array return

---

README.md
packages/graphql/src/schema/resolvers/cypher.ts
packages/graphql/tests/integration/cypher.int.test.ts
packages/graphql/tests/integration/issues/#315.int.test.ts

Merge 1.2.1 changes from master into 2.0.0

---

packages/graphql/src/translate/create-update-and-params.ts
packages/graphql/tests/integration/relationship-properties/update.int.test.ts

Fixes #337 by accessing correct property in order to assign relationship variable to have an accurate translation of the cypher query.
- #337 

Fix relationship assignment for update.update

---

packages/graphql/src/translate/translate-update.ts
packages/graphql/tests/integration/relationship-properties/update.int.test.ts

Fixes #336 by adding the correct parameters from `createSetRelationshipPropertiesAndParams` to `cypherParams`
- #336 

Fix cypher params for update.create

---

docs/asciidoc/troubleshooting.adoc
packages/graphql/src/classes/Neo4jGraphQL.ts
packages/graphql/src/index.ts
packages/graphql/src/types.ts
packages/graphql/src/utils/execute.test.ts
packages/graphql/src/utils/execute.ts

Allows for optional setting of Cypher query options from https://neo4j.com/docs/cypher-manual/current/query-tuning/query-options/#cypher-query-options
Needs documentation - either https://neo4j.com/docs/graphql-manual/current/drivers-and-config/ or https://neo4j.com/docs/graphql-manual/current/troubleshooting/?

Allow for the optional setting of Cypher query options

---

packages/graphql/tests/integration/query-options.int.test.ts

As per title, there should have been at least one integration test with query options enabled.

Add quick integration test to show queries run with query options

---

packages/graphql/src/schema/make-augmented-schema.ts
packages/graphql/src/schema/pagination.ts
packages/graphql/src/translate/connection/create-connection-and-params.test.ts
packages/graphql/src/translate/connection/create-connection-and-params.ts
packages/graphql/tests/integration/connection-resolvers-int.test.ts
packages/graphql/tests/integration/connections/unions.int.test.ts
packages/graphql/tests/tck/tck-test-files/.markdownlint.json
packages/graphql/tests/tck/tck-test-files/cypher/connections/projections/projections.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/unions.md
packages/graphql/tests/tck/tck-test-files/schema/connections/enums.md
packages/graphql/tests/tck/tck-test-files/schema/connections/sort.md
packages/graphql/tests/tck/tck-test-files/schema/connections/unions.md
packages/graphql/tests/tck/tck-test-files/schema/directives/exclude.md
packages/graphql/tests/tck/tck-test-files/schema/interfaces.md
packages/graphql/tests/tck/tck-test-files/schema/issues/162.md
packages/graphql/tests/tck/tck-test-files/schema/relationship-properties.md
packages/graphql/tests/tck/tck-test-files/schema/relationship.md
packages/graphql/tests/tck/tck-test-files/schema/unions.md

Addresses some bugs introduced with cursor-based pagination, and adds more test cases.
- No longer assume that `edges` in the resolve tree - this was safe to assume before, but now `totalCount` or `pageInfo` can be present instead
- Project `__resolveType` for unions to allow for calculation of `totalCount`, but filter out before return to match fragments in the selection set
- Don't return `edges` in Cypher unless it's necessary - this is when either `edges` or `pageInfo` have been asked for
Problems still to discuss and address:
- ~~`startCursor` and `endCursor` - nullable or non-nullable? The spec says that they are non-nullable (https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo.Fields), but there is a longstanding PR to change this …

Return totalCount if no edges, and prevent errors for accessing undefined properties

---

packages/graphql/package.json
packages/graphql/src/classes/Neo4jGraphQL.ts
packages/graphql/tests/integration/issues/349.int.test.ts
yarn.lock

It appears that despite promising to be fixed in version 6.0.10 (https://github.com/ardatan/graphql-tools/releases/tag/v6.0.10), `addResolversToSchema` in `@graphql-tools/schema` breaks schema directives. So this is a workaround for that bug, adding schema directives after resolvers have been added.
Also changed constructor types around for this field so hopefully `SchemaDirectiveVisitor` can be used directly from `@graphql-tools/utils` without recasting.
#349

Manually add schemaDirectives after resolvers

---

docs/asciidoc/auth/authentication.adoc
packages/graphql/src/schema/get-auth.ts
packages/graphql/src/translate/create-auth-and-params.test.ts
packages/graphql/src/translate/create-auth-and-params.ts
packages/graphql/src/types.ts
packages/graphql/tests/integration/auth/allow-unauthenticated.int.test.ts
packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/arguments/allow.md
packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/arguments/bind.md
packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/arguments/where.md
packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/projection.md
packages/graphql/tests/tck/tck-test-files/cypher/union.md

Add allowUnauthenticated parameter in auth rules to avoid throwing exceptions if no auth is provided.
**Changes:**
- Update documentation `auth/authentication`.
- If `paramValue` is `undefined` inject `false` instead of the previous condition `key = $param`, as it should always be falsy
- Fix a small issue: if a `paramValue` is `null`, `apoc.validate` raise an exception if the check is done like this `value = null`. So I just replaced the condition for it to be `value IS null` ([more infos](https://community.neo4j.com/t/neo-clienterror-procedure-procedurecallfailed-with-apoc-do-when/14017/12))
- Fix the 4.3.0 Neo4J deprecation of `EXISTS()` with recommanded `IS NOT NULL`. ([more infos](https://neo4j.com/docs/cypher-manual/current/deprecations-additions-removals-compatibility/#:~:text=ASSER …

feat(graphql): add allowUnauthenticated parameter to auth rules

---

packages/graphql/package.json
packages/graphql/src/schema/make-augmented-schema.ts
packages/graphql/src/schema/resolvers/create.ts
packages/graphql/src/schema/resolvers/defaultField.ts
packages/graphql/src/schema/resolvers/index.ts
packages/graphql/src/schema/resolvers/update.ts
packages/graphql/src/translate/create-projection-and-params.ts
packages/graphql/src/translate/translate-create.ts
packages/graphql/src/translate/translate-update.ts
packages/graphql/tests/integration/issues/350.int.test.ts
packages/graphql/tests/tck/tck-test-files/cypher/alias.md

This pull request adds the ability to alias fields multiple times in queries. Currently when translating a graqhql request into a cypher query, the field name is used as opposed to the alias provided. Since the default field resolver also uses the field name this went unnoticed as long as any field was aliased at most one time during a query. However, as noted in #350 and described in detail in https://github.com/neo4j/graphql/issues/350#issuecomment-885957460; if a field is aliased multiple times, the use of the field name in the projection causes the last defined aliased field to override the others.
Aliasing of fields also requires to modify the returned object from the `create` and `update` resolver by making the key the aliased field.
- #350 
The following requirements should have …

Fix for field with multiple aliases

---

docs/asciidoc/auth/authentication.adoc
packages/graphql/src/schema/get-auth.ts
packages/graphql/src/schema/make-augmented-schema.ts
packages/graphql/src/schema/resolvers/create.ts
packages/graphql/src/schema/resolvers/defaultField.ts
packages/graphql/src/schema/resolvers/index.ts
packages/graphql/src/schema/resolvers/update.ts
packages/graphql/src/translate/create-auth-and-params.test.ts
packages/graphql/src/translate/create-auth-and-params.ts
packages/graphql/src/translate/create-projection-and-params.ts
packages/graphql/src/translate/create-where-and-params.ts
packages/graphql/src/translate/translate-create.ts
packages/graphql/src/translate/translate-update.ts
packages/graphql/src/types.ts
packages/graphql/tests/integration/auth/allow-unauthenticated.int.test.ts
packages/graphql/tests/integration/issues/350.int.test.ts
packages/graphql/tests/integration/issues/360.int.test.ts
packages/graphql/tests/tck/tck-test-files/cypher/alias.md
packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/arguments/allow.md
packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/arguments/bind.md
packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/arguments/where.md
packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/projection-connection-union.md
packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/projection-connection.md
packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/projection.md
packages/graphql/tests/tck/tck-test-files/cypher/issues/360.md
packages/graphql/tests/tck/tck-test-files/cypher/union.md

As per title. Must be merge committed.

Merge master into 2.0.0

---

packages/ogm/src/classes/Model.ts

Allow OGM selectionSet to be SelectionSetNode.
#216

Allow OGM selectionSet to be SelectionSetNode

---

packages/graphql/package.json
packages/graphql/src/schema/make-augmented-schema.ts
packages/graphql/src/schema/to-compose.ts
packages/ogm/package.json
yarn.lock

Patch upgrades for most dependencies, holding off of upgrading `@graphql-tools/schema` and `@graphql-tools/utils` to 8.x because of _massively_ breaking changes.
Note that `@graphql-tools/merge` is pinned at 6.2.14 because 6.2.15 and higher depend on `@graphql-tools/schema` and `@graphql-tools/utils` 8.x, despite being a patch version upgrade.
`graphql-compose` upgraded to 9.x and bugs resulting from breaking changes fixed.

Dependency upgrades

---

packages/graphql/src/schema/make-augmented-schema.ts
packages/graphql/src/schema/pagination.test.ts
packages/graphql/src/schema/pagination.ts
packages/graphql/src/translate/create-projection-and-params.ts
packages/graphql/tests/integration/connections/alias.int.test.ts
packages/graphql/tests/tck/tck-test-files/cypher/connections/alias.md

Adds the ability to alias a connection and the selections inside of it.

Alias connections

---

packages/graphql/src/schema/make-augmented-schema.test.ts
packages/graphql/src/schema/make-augmented-schema.ts

Throws error when `@auth` is used on relationship props. This is not supported and we assume that the parent nodes auth is sufficient enough.

Error auth relationship properties

---

packages/graphql/tests/integration/teardown.ts

Will need to be used to avoid hitting the 50,000 node limit when testing against Aura Free (would take a while, but would be a nuisance).

Adds a simple util file which can be called to teardown database

---

packages/graphql/src/schema/make-augmented-schema.test.ts
packages/graphql/src/schema/make-augmented-schema.ts

Throws when relationship directive is used on relationship properties. Related: #379

Error relationship on relationship properties

---

docs/asciidoc/introduction.adoc
packages/graphql/package.json
packages/graphql/src/constants.ts
packages/graphql/src/utils/verify-database.test.ts
packages/graphql/src/utils/verify-database.ts
yarn.lock

Following reports that our changes to connect operations no longer work on 4.1.0, I iterated through versions to find the minimum which we now support - 4.1.5 is where all tests start passing.
Also fixes version checking, now uses `semver` package for comparison. For non-semantic APOC version, strips off the trailing number.
Also, now throws all compatibility issues in one error, rather than throwing as soon as it hits each.
Worthwhile adding an integration test pipeline for 4.1.5 exactly (rather than 4.1.x as current, I'm assuming 4.1.9) so we can easily tell if and when we break compatibility? 

Change minimum database version to 4.1.5

---

packages/graphql/src/schema/resolvers/cypher.ts
packages/graphql/src/translate/create-projection-and-params.ts
packages/graphql/tests/integration/issues/387.int.test.ts
packages/graphql/tests/tck/tck-test-files/cypher/issues/387.md
packages/graphql/tests/tck/tck.test.ts

Fix the use of custom scalar/enum values as return type for custom Cypher
#387 

Fix the use of custom scalar/enum values as return type for custom Cypher

---

packages/graphql/src/index.ts

Exports the auth error classes so one can override the messages, reference https://discord.com/channels/787399249741479977/818578492723036210/872962949445193748

feat: export auth errors from index

---

docs/asciidoc/ogm/selection-set.adoc
packages/graphql/src/constants.ts
packages/graphql/src/schema/make-augmented-schema.test.ts
packages/graphql/src/schema/make-augmented-schema.ts

Throws error when the user uses reserved names on types, interfaces and interface fields. This is mainly to stop any conflicts with Relay.

Reserved properties

---

packages/graphql/src/schema/resolvers/cypher.ts
packages/graphql/tests/integration/cypher.int.test.ts

Fix multiple connections being returned from custom Cypher
Variable being reassigned in a loop. 😞 
Reported in Discord: https://discord.com/channels/787399249741479977/818578492723036210/873251861648515122

Fix multiple connections being returned from custom Cypher

---

docs/asciidoc/guides/2.0.0-migration/miscellaneous.adoc
packages/graphql/src/schema/make-augmented-schema.ts
packages/graphql/src/translate/create-where-and-params.ts
packages/graphql/src/translate/where/create-node-where-and-params.ts
packages/graphql/tests/tck/tck-test-files/schema/issues/162.md

Let's take the opportunity of this breaking release to remove some surplus requirements, `_IN` and `_NOT_IN` for one-to-many and one-to-one relationships. We don't currently treat these relationship cardinalities differently anywhere else, the filters are completely untested, and the same filters can be achieved through other means (see migration guide for example).

Remove surplus _IN and _NOT_IN filters for relationships

---

packages/graphql/src/translate/connection/create-connection-and-params.ts
packages/graphql/tests/integration/connections/alias.int.test.ts
packages/graphql/tests/integration/connections/nested.int.test.ts
packages/graphql/tests/tck/tck-test-files/cypher/connections/alias.md

Similar to #359, this adds the ability to have multiple aliases on connection fields without overwriting parameters by naming parameters after aliases and fields after names.
- #392

Fix for aliasing connection multiple times

---

docs/antora/antora.yml

Removes the prerelease marker from the Antora component descriptor, which means 2.0 is included as the latest release in the version drop-down.

Remove prerelease marker

---

packages/graphql/src/translate/connection/create-connection-and-params.test.ts
packages/graphql/src/translate/connection/create-connection-and-params.ts
packages/graphql/tests/tck/tck-test-files/cypher/connections/alias.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/composite.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/node/and.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/node/arrays.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/node/equality.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/node/numerical.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/node/or.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/node/points.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/node/string.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/relationship/and.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/relationship/arrays.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/relationship/equality.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/relationship/numerical.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/relationship/or.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/relationship/points.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/relationship/string.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/relationship/temporal.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/mixed-nesting.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/projections/create.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/projections/projections.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/projections/update.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/relationship-properties.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/relationship_properties/connect.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/relationship_properties/create.md
packages/graphql/tests/tck/tck-test-files/cypher/connections/unions.md
packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/arguments/where.md
packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/projection-connection-union.md
packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/projection-connection.md

Fixes remnant relationship variable not suffixed with "_relationship".
#412

Resolve node/relationship variable naming collision

---

packages/graphql/src/schema/resolvers/defaultField.ts
packages/graphql/tests/integration/issues/388.int.test.ts

Given a custom Cypher field like the following:
```graphql
type Query {
getContent(userID: ID): [Content]
@cypher(
statement: """
MATCH (myUser:User {id: $userID})
OPTIONAL MATCH (myUser)-[:HAS_FRIEND]->(myFriends:User)
CALL {
WITH myUser, myFriends
MATCH (myUser)-[:HAS_POST]->(post:Post)
RETURN post
UNION
WITH myUser, myFriends
MATCH (myFriends)-[:HAS_POST]->(post:Post)
RETURN post
}
RETURN DISTINCT apoc.map.merge(properties(post), { __resolveType: 'Post' }) AS result ORDER BY result.modifiedDate DESC
"""
)
}
```
It's impossible/very difficult to account for field aliasing in the return results, for example with a query like:
```graphql
query GetContent($userID: ID) {
getContent(userID: $userID) {
__typename
... on Post {
postContent: content
}
}
}
```
So instead, in the default field …

Aliased fields from custom Cypher

---

packages/graphql/src/translate/translate-create.ts
packages/graphql/tests/integration/create.int.test.ts
packages/graphql/tests/tck/tck-test-files/cypher/operations/create.md

Proposed fix for #427 wherein `projection` parameters are incorrectly replaced when translating the `create` mutation. The proposed change is to replace parameter reassignments prior to replacing parameters and node names.
- #427 

Fix incorrect replacement of projection parameters in translateCreate

---

packages/graphql/src/translate/where/create-node-where-and-params.ts
packages/graphql/tests/integration/connections/filtering.int.test.ts
packages/graphql/tests/tck/tck-test-files/cypher/connections/filtering/node/relationship.md

Propose fix for #437 wherein the variable in the pattern comprehension is set to `relatedNodeVariable` as opposed to `param`.
- #437 

Fix variable assignment for filtering on relationship node in connections

---

packages/graphql/src/schema/to-compose.ts
packages/graphql/tests/integration/alias.int.test.ts

This fixes an issue brought up in https://github.com/neo4j/graphql/issues/388#issuecomment-901340465. When composing object fields the `ID`, `Int`, and `Float` fields are being given a `resolve` that does not use the default resolver needed for aliasing.
This PR first extracts the value given from the `defaultFieldResolver` before checking it.

Fix aliasing of ID, Int, and Float fields

---

packages/graphql/src/schema/validation/enums.ts
packages/graphql/src/schema/validation/validate-document.test.ts
packages/graphql/src/schema/validation/validate-document.ts

Filters out any fields returning a `*MutationResponse` object, and adds `SortDirection` to validation schema.
#442 

Allow MutationResponse and SortDirection through validation

---

packages/graphql/src/schema/resolvers/count.test.ts
packages/graphql/src/schema/resolvers/count.ts
packages/graphql/src/schema/resolvers/create.ts
packages/graphql/src/schema/resolvers/cypher.ts
packages/graphql/src/schema/resolvers/delete.ts
packages/graphql/src/schema/resolvers/read.ts
packages/graphql/src/schema/resolvers/update.ts
packages/graphql/src/utils/execute.test.ts
packages/graphql/src/utils/execute.ts

So far, just a refactor of `execute.ts`, and figured sensible to review that before introducing the tonne of TCK test changes associated with adding the bookmark return to the schema.
This has replaced a load of usages of private fields in the driver with the actual fields which should be used for these purposes.
Bookmark needed to allow users to read their own rights, especially important when dealing with causal clusters.

Refactor of execute.ts ahead of adding bookmark return

---

packages/graphql/src/translate/connection/create-connection-and-params.ts
packages/graphql/tests/integration/issues/433.int.test.ts
packages/graphql/tests/tck/tck-test-files/cypher/issues/433.md

Check if where is truthy before adding to `whereStrs`. 
Fixes: #433 

Fix/433 - Exclude empty where from cypher generation

---

.github/workflows/pull-requests.yml

Disable fail-fast for integration tests - useful for us to be able to see which versions tests fail on

Disable fail-fast for integration tests

---

docs/modules/ROOT/pages/directives.adoc
docs/modules/ROOT/pages/guides/migration-guide/type-definitions.adoc
docs/modules/ROOT/pages/type-definitions/basics.adoc
docs/modules/ROOT/pages/type-definitions/relationships.adoc
packages/graphql/src/schema/validation/directives.ts
packages/graphql/src/schema/validation/validate-document.test.ts
packages/graphql/tests/tck/tck-test-files/schema/relationship-properties.md

Optional syntactic sugar directive to help users distinguish between interfaces used for relationship properties, and otherwise.

Add @relationshipProperties directive

---

docs/modules/ROOT/pages/type-definitions/types.adoc
packages/graphql/src/schema/get-where-fields.ts
packages/graphql/src/schema/scalars/Time.ts
packages/graphql/src/schema/scalars/index.ts
packages/graphql/tests/integration/types/time.int.test.ts
packages/graphql/tests/tck/tck-test-files/cypher/types/time.md
packages/graphql/tests/tck/tck-test-files/schema/types/time.md

Adds a `Time` scalar. It is passed in as an RFC 3339 compliant time string and stored in the database as a neo4j `Time` instance.

Feature: Add Time Scalar

---

docs/modules/ROOT/pages/type-definitions/types.adoc
packages/graphql/src/schema/get-where-fields.ts
packages/graphql/src/schema/scalars/LocalTime.ts
packages/graphql/src/schema/scalars/index.ts
packages/graphql/tests/integration/types/localtime.int.test.ts
packages/graphql/tests/tck/tck-test-files/cypher/types/localtime.md
packages/graphql/tests/tck/tck-test-files/schema/types/localtime.md

Adds a `LocalTime` scalar. It is passed in as a time string without timezone information and stored in the database as a neo4j `LocalTime` instance.

Feature: Add LocalTime Scalar

---

docs/modules/ROOT/pages/type-definitions/types.adoc
packages/graphql/src/schema/get-where-fields.ts
packages/graphql/src/schema/scalars/LocalDateTime.ts
packages/graphql/src/schema/scalars/index.ts
packages/graphql/tests/integration/types/localdatetime.int.test.ts
packages/graphql/tests/tck/tck-test-files/cypher/types/localdatetime.md
packages/graphql/tests/tck/tck-test-files/schema/types/localdatetime.md

Adds a `LocalDateTime` scalar. It is passed in as an ISO 8601 datetime string without timezone information and stored in the database as a neo4j `localdatetime` value.
This allows for ISO 8601 datetime strings in the extended format: `YYYY-MM-DDTHH:MM:SS`
- #274 

Feature: Add LocalDateTime Scalar

---

.github/workflows/main.yml

No longer skip particular integration tests against Aura - drop has now been updated and will pass.

Update GitHub Actions Aura Integration tests

---

.eslintrc.js
.gitignore
packages/graphql/src/classes/Neo4jGraphQL.ts

Adds a return of the obj parameter, this seems to be the expected way of using addSchemaLevelResolver. Its omission was causing the missing results in subscription payload when using neo4j/graphql library
#212 
It's important that changes are discussed in advance to make sure we choose the right solution and to avoid duplication of effort.

Fix missing subscription payload

---

.gitignore
packages/graphql/src/schema/resolvers/count.test.ts
packages/graphql/src/schema/resolvers/delete.test.ts
packages/graphql/src/schema/resolvers/read.test.ts
packages/graphql/src/translate/create-auth-and-params.test.ts
packages/graphql/src/translate/create-projection-and-params.test.ts
packages/graphql/src/translate/create-update-and-params.test.ts
packages/graphql/src/translate/create-where-and-params.test.ts
packages/graphql/src/utils/test/node-builder.ts

Using NodeBuilder in tests we can avoid typecasting and remove several mock properties

Remove Node casting in tests

---

packages/graphql/src/schema/make-augmented-schema.ts
packages/graphql/src/translate/create-connect-and-params.ts
packages/graphql/src/translate/create-create-and-params.ts
packages/graphql/src/translate/translate-update.ts
packages/graphql/tests/schema/relationship-properties.test.ts
packages/graphql/tests/tck/tck-test-files/cypher/operations/update.md

Proposed fix for #496. Current behavior is to create an `edge` and thereby a `CreateInput` and `UpdateInput` for relationship properties if they exist. This PR will strip out generated fields (`@id`, `@timestamp`) before adding these edges to the schema.
- #496 

Fix: Creation of Empty `{Create,Update}Input` for Relationship Properties

---

packages/graphql/src/translate/create-projection-and-params.ts
packages/graphql/tests/integration/unions.int.test.ts
packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/arguments/where.md
packages/graphql/tests/tck/tck-test-files/cypher/directives/node/node-label-union.md
packages/graphql/tests/tck/tck-test-files/cypher/nested-unions.md
packages/graphql/tests/tck/tck-test-files/cypher/union.md

Proposed fix for #493. Current behavior returns null values. This PR filters out null values.
- #493 

Fix: Filter Null Values In Union Relationship

---

packages/graphql/src/translate/create-auth-and-params.test.ts
packages/graphql/src/translate/create-auth-and-params.ts
packages/graphql/src/utils/join-predicates.test.ts
packages/graphql/src/utils/join-predicates.ts
packages/graphql/tests/integration/issues/505.int.test.ts

Complex auth rules, combined with where filters can generate cypher queries with invalid predicate precedence which evaluate incorrectly.
Type definitions
simplified for readability
```
type Person {
id: ID! @id(autogenerate: false)
authId: String
workspaces: [Workspace] @relationship(type: "MEMBER_OF", direction: OUT)
adminOf: [Workspace] @relationship(type: "HAS_ADMIN", direction: IN)
}
type Workspace @auth(rules: [
{ 
operations: [READ],
roles: ["""member"""],
where: { 
OR: [
{ members_INCLUDES: { authId: """$jwt.sub""" } }
{ admins_INCLUDES: { authId: """$jwt.sub""" } }
]
}
},
{
operations: [READ, CREATE, UPDATE, CONNECT, DISCONNECT, DELETE ]
roles: ["""admin"""]
},
]) @exclude(operations: [CREATE, UPDATE]) {
id: ID! @id(autogenerate: false)
name: String!
members: [Person!] …
```

fix: wrap auth sub clauses in parentheses to preserve precedence

---

docs/modules/ROOT/pages/type-definitions/access-control.adoc

Fixes the documentation for the `operations` argument in `@exclude` directive.
#522 

Fix access-control.adoc operations field for @exclude directive

---

packages/graphql/src/schema/validation/directives.ts

I don't know how this worked before, this PR simply called `new` on a class that should be invoked.

Fix: call new on GraphQLString

---

packages/graphql/src/schema/resolvers/create.ts
packages/graphql/src/schema/resolvers/update.ts
packages/graphql/src/translate/translate-create.ts
packages/graphql/src/translate/translate-update.ts
packages/graphql/tests/integration/issues/only-info.test.ts

fix: error when only selecting info on update and create operations

---

docs/markdown/DEVELOPING.md
docs/modules/ROOT/pages/auth/setup.adoc
packages/graphql/package.json
packages/graphql/src/auth/get-jwt.ts
packages/graphql/src/classes/Neo4jGraphQL.ts
yarn.lock

According to OpenID configuration, verification of JWTs should be validated against the authentication server's JWKS to ensure that the server signed it. Instead of interpreting the JWT via a secret or PEM file (which if maliciously stolen, could rewrite JWTs), we verify via the signature represented by the token's kid at the endpoint `https://YOUR_DOMAIN/.well-known/jwks.json`. 
These changes are currently non-breaking changes.
#252 
Passing a decoded token only partially solves this verification issue. We'd rather perform verification via the GraphQL @auth directive so checks occur at each request and are done **without secrets**.

Added OpenID Json Web Key Sets for verification via the @auth directive

---

packages/graphql/src/translate/create-projection-and-params.ts
packages/graphql/tests/integration/issues/date-in-edge.test.ts

The error that gets thrown:
```
Neo4jError: Invalid input 'iso_zoned_date_time': expected
"!="
"%"
")"
"*"
"+"
","
"-"
"."
"/"
":"
"<"
"<="
"<>"
"="
"=~"
">"
">="
"AND"
"CONTAINS"
"ENDS"
"IN"
"IS"
"OR"
"STARTS"
"XOR"
"["
"^" (line 6, column 97 (offset: 375))
"WITH collect({ node: { birthday: apoc.date.convertFormat(toString(this_movies_actor.birthday), "iso_zoned_date_time", "iso_offset_date_time") } }) AS edges"
```
Generated Cypher:
```
MATCH (this:Genre)
WHERE this.id = $this_id
RETURN this { movies: [ (this)-[:MOVIE]->(this_movies:Movie)   | this_movies { actorsConnection: apoc.cypher.runFirstColumn("CALL {
WITH this_movies
MATCH (this_movies)-[this_movies_actor_relationship:ACTOR]->(this_movies_actor:Actor)
WITH collect({ node: { birthday: …
```

Querying DateTime in the edge of a connection throws an error

---

packages/graphql/package.json
packages/graphql/src/schema/make-augmented-schema.ts
packages/graphql/tests/integration/issues/586.int.test.ts
yarn.lock

Updating graphql-compose from 9.0.3 to 9.0.4 causes `make-augmented-schema` to break when using the following typedefs:
```
input TestInput {
id: BigInt = "0"
}
```
This is due to type BigInt not being defined before `extraDefinitions` are added
A test was added to ensure this behavior does not happen again, but keep in mind that this is not reproducible with graphql-compose < 9.04
#586

Generate scalar typedefs before extra definitions

---

packages/graphql/src/translate/create-projection-and-params.ts
packages/graphql/tests/tck/tck-test-files/connections/mixed-nesting.test.ts
packages/graphql/tests/tck/tck-test-files/issues/601.test.ts
packages/graphql/tests/tck/tck-test-files/operations/create.test.ts

See https://github.com/neo4j/graphql/pull/603/files#diff-59603a7b1cd33f04edc84f5a9aa4efdfb4a5aace657c247ea4b3a1e0850e26d5R102 in the new TCK test file where the `$auth` parameter has been added as needed.
#601 

Fix for missing auth parameter

---

packages/introspector/src/transforms/neo4j-graphql/graphql.ts
packages/introspector/src/transforms/neo4j-graphql/utils/create-relationship-fields.ts
packages/introspector/src/transforms/neo4j-graphql/utils/generate-graphql-safe-name.test.ts
packages/introspector/src/transforms/neo4j-graphql/utils/generate-graphql-safe-name.ts
packages/introspector/src/tsconfig.json
packages/introspector/tests/integration/graphql/graphs.test.ts
packages/introspector/tests/integration/graphql/nodes.test.ts

Two fixes for the introspector:
- Create correct non-nullable arrays for relationships.
- Don't generate invalid type/interface names with regards to node labels and rel-types that starts with invalid characters (i.e. numbers).
For the last point, the integration test assertion with Neo4j GraphQL is commented out due to lack of support in the library for labels starting with numbers.
fyi: I deliberately named this in a way so it doesn't show up in changelogs.

Introspector fixes

---

packages/graphql/src/classes/Node.test.ts
packages/graphql/src/classes/NodeDirective.test.ts
packages/graphql/src/classes/NodeDirective.ts
packages/graphql/tests/tck/tck-test-files/aggregations/field-level-aggregations/field-level-aggregations-labels.test.ts
packages/graphql/tests/tck/tck-test-files/aggregations/label.test.ts
packages/graphql/tests/tck/tck-test-files/aggregations/where/node.test.ts
packages/graphql/tests/tck/tck-test-files/directives/node/node-additional-labels.test.ts
packages/graphql/tests/tck/tck-test-files/directives/node/node-label-jwt.test.ts
packages/graphql/tests/tck/tck-test-files/directives/node/node-label-union.test.ts
packages/graphql/tests/tck/tck-test-files/directives/node/node-label.test.ts
packages/graphql/tests/tck/tck-test-files/directives/node/node-plural.test.ts
packages/graphql/tests/tck/tck-test-files/directives/node/node-with-auth-projection.test.ts
packages/graphql/tests/tck/tck-test-files/directives/node/node-with-auth.test.ts

Escape all labels set in the @node directive label to ensure these are valid cypher labels

Fix: Escape all @node directive labels

---

packages/graphql/package.json
yarn.lock

It appears that the 9.0.5 release of `graphql-compose` expects GraphQL 16.x, as can be seen in the recent failures of our package tests. This PR pins it to 9.0.4 for now - this should be undone when we upgrade to GraphQL 16.x.

Pin graphql-compose to 9.0.4 until we have upgraded to GraphQL 16.x

---

packages/graphql/src/tsconfig.json

Through various merges, the TypeScript build somehow became broken. Fixed by adding `"exclude": ["**/*.test.ts"]` to the `tsconfig.json` file in `packages/graphql/src`. This, however, is not the right fix for this problem, because ESLint requires these files to be included in the TypeScript build.
The correct solution would be to add the test directory as a project reference, however this results in a circular dependency. This is because of the builders which are used by files in both `src` and `tests`, and they also use files from `src`. This needs addressing.
However, this gets us unblocked for now.

Fix TypeScript build

---

.github/labeler.yml
.github/workflows/pull-requests.yml
.markdownlint.json
README.md
renovate.json

- Turn on Renovate automerge for all but major dependency upgrades
- Add "dependency upgrade" label to PRs for releasable dependency upgrades (not dev dependencies)
- Only add package labels for releasable dependency upgrades (not dev dependencies)
- Run package tests in pull requests - these have previously caught bad dependency upgrades
Also added a little line to the README for dev and master.

Renovate automerge and labelling

---

packages/graphql/src/schema/create-relationship-fields/index.ts
packages/graphql/tests/schema/comments.test.ts

This PR addresses #764 by adding the description field.
- #764 

Fix: Missing Relationship Description

---

packages/graphql/src/translate/connect-or-create/create-connect-or-create-and-params.ts
packages/graphql/tests/integration/issues/619.int.test.ts

This PR fixes an error when `connectOrCreate` is used in 1-to-1 relationships
#619

Fix/619 input.map is not a function error in connectOrCreate

---

.github/workflows/docs-build.yml
.github/workflows/docs-teardown.yml
.github/workflows/feature-request.yml
.github/workflows/issue-labeled.yml
.github/workflows/labeler.yml
.github/workflows/lint-markdown.yml
.github/workflows/project-card-moved.yml
.github/workflows/pull-requests.yml
.github/workflows/sonarcloud.yml

Pull request jobs will now run off pull requests to `master`.
If a bug is given high priority, add a label and create a comment about branching from `master`. Didn't see the point of doing this for low priority bugs as this is "business as usual".
Adds new feature requests to project just to keep things tidy whilst we decide what to do here.
Any other tweaks we need to make?

GitHub Actions: pipeline on `master` PRs, high priority label/comment

---

docs/rfcs/rfc-005-query-limits.md

This PR updates the rfc to cover both options `default` and `max`.
The proposed solution, involves the following arguments for `queryOptions`:
```
@queryOptions(limit: {default: 5, max: 10}) {
```
Alternatively, 2 separate arguments could be used:
```
@queryOptions(defaultLimit: 5, maxLimit: 10) {
```

Adds default and max options to limit

---

packages/graphql/src/translate/where/create-node-where-and-params.ts
packages/graphql/tests/integration/issues/894.int.test.ts
packages/graphql/tests/tck/tck-test-files/issues/894.test.js
packages/graphql/tests/tck/tck-test-files/issues/894.test.ts

Using DBpropertyName instead of fieldName for node where clause.
https://github.com/neo4j/graphql/issues/894

Fix/Disconnect Where Args Not Implementing Aliases

---

docs/modules/ROOT/pages/auth/setup.adoc
packages/graphql/tests/integration/directives/auth/roles.int.test.ts

Test and document case where `rolesPath` contains dot character.
This was reported as a bug a long time ago but in the end has just turned out to be an error in documentation.
Closes #241

Test and document case where rolesPath contains dot character

---

packages/graphql/src/translate/connect-or-create/create-connect-or-create-and-params.ts
packages/graphql/src/translate/create-create-and-params.ts
packages/graphql/src/translate/create-update-and-params.ts
packages/graphql/src/translate/translate-update.ts
packages/graphql/tests/integration/connect-or-create/connect-or-create-auth.int.test.ts
packages/graphql/tests/integration/issues/923.int.test.ts
packages/graphql/tests/tck/tck-test-files/connections/connect-or-create/connect-or-create-auth.test.ts
packages/graphql/tests/tck/tck-test-files/connections/connect-or-create/connect-or-create-unions.test.ts
packages/graphql/tests/tck/tck-test-files/connections/connect-or-create/connect-or-create.test.ts

Wraps the created cypher statement for connectOrCreate mutations in create-create-and-params with a CALL subquery lead by a WITH.
Fixes #923
Closes:
- #923

Fix: #923 connectOrCreate throws error when used with auth

---

packages/graphql/tests/integration/connections/interfaces.int.test.ts

The test `interfaces.int.test` can fail due to a non-empty database as it is using global `Actor` `Movie` and `Series` types. Refactored into using unique types

Use unique types in interfaces.int.test

---

packages/graphql/package.json
packages/introspector/package.json
packages/ogm/package.json

As discussed, Clicking the npm link to homepage should redirect to our default branch instead of master

Update package.json homepage path to dev

---

.eslintrc.js
packages/graphql/src/schema/resolvers/cypher.ts
packages/graphql/src/translate/utils/stringify-object.ts
packages/ogm/src/classes/Model.ts

This rule has been caused false negatives in eslint, as we **do** want some underscore variables (for now at least)
Additionally, a couple of low-hanging-fruit eslint errors fixed

Update dangle_underscore eslint rule

---

docs/modules/ROOT/pages/type-definitions/database-mapping.adoc
packages/graphql/src/classes/Node.test.ts
packages/graphql/src/classes/Node.ts
packages/graphql/src/schema/make-augmented-schema.ts
packages/graphql/src/schema/resolvers/create.ts
packages/graphql/src/schema/resolvers/update.ts
packages/graphql/src/schema/validation/directives.ts
packages/graphql/src/translate/translate-create.ts
packages/graphql/src/translate/translate-update.ts
packages/graphql/tests/integration/issues/235.int.test.ts
packages/graphql/tests/integration/issues/288.int.test.ts
packages/graphql/tests/schema/issues/1038.test.ts
packages/graphql/tests/schema/pluralize-consistency.test.ts
packages/graphql/tests/tck/tck-test-files/issues/288.test.ts
packages/graphql/tests/utils/graphql-types.ts
packages/introspector/tests/integration/graphql/nodes.test.ts
packages/ogm/package.json
packages/ogm/src/classes/Model.ts
packages/ogm/src/classes/OGM.ts
packages/ogm/src/generate.ts
packages/ogm/tests/utils.ts

We made some glaring oversights in how we generate plural strings of type names in 3.0.0. This PR attempts to rationalise that behaviour, and add more tests.
Closes #1038

Reintroduce camelcase for generating field names

---

docs/rfcs/rfc-009-graphql-ui-poc.md

RFC for a successor of the [GraphQL Architect](https://grandstack.io/docs/graphql-architect-overview/#:~:text=GraphQL%20Architect%20is%20a%20graph,Neo4j%20Desktop%20Graph%20Apps%20Gallery).

RFC: Successor for GraphQL Architect

---

packages/graphql/tests/utils/graphql-types.ts

This PR changes the unique types used for testing so these are now a class. All works exactly the same, however, the following are also valid:
```typescript
const typeMovie = new UniqueType("Movie"); // Same as generateUniqueType("Movie")
const typedefs = `type ${typeMovie}`; // Same as `type ${typeMovie.name}`
```

turn unique types into classes instances

---

packages/graphql/src/utils/execute.test.ts
packages/graphql/src/utils/execute.ts

Overriding the driver useragent is not a reliable way of getting the details of the Neo4j GraphQL Library into the Neo4j query log. This instead writes those details to the transaction metadata, which are also available to view in logs.

Write details to transaction metadata instead of useragent

---

packages/graphql/src/translate/cypher-builder/build-merge-statement.ts
packages/graphql/src/translate/cypher-builder/build-node-statement.ts
packages/graphql/tests/tck/tck-test-files/issues/1131.test.ts

When generating the initial `MERGE` in a `connectOrCreate`, the input `where` object was not being checked against aliases for database properties. This adds that check.
Closes #1131.

Make sure aliases are checked against connectOrCreate where input

---

packages/graphql/src/translate/create-connect-and-params.ts
packages/graphql/src/translate/create-disconnect-and-params.ts
packages/graphql/tests/integration/issues/1132.int.test.ts
packages/graphql/tests/tck/tck-test-files/directives/auth/arguments/allow/allow.test.ts
packages/graphql/tests/tck/tck-test-files/directives/auth/arguments/allow/inherited.test.ts
packages/graphql/tests/tck/tck-test-files/directives/auth/arguments/allow/interface-relationships/implementation-allow.test.ts
packages/graphql/tests/tck/tck-test-files/directives/auth/arguments/allow/interface-relationships/interface-allow.test.ts
packages/graphql/tests/tck/tck-test-files/directives/auth/arguments/roles/roles.test.ts
packages/graphql/tests/tck/tck-test-files/issues/1132.test.ts

`Allow` rule is checked against target node rather than the source node.
The issue: https://github.com/neo4j/graphql/issues/1132
Closes:
- https://github.com/neo4j/graphql/issues/1132

Fix: #1132, CONNECT and DISCONNECT auth rules check allow rules against target node instead of source

---

packages/graphql/src/translate/create-projection-and-params.ts
packages/graphql/tests/integration/issues/1050.int.test.ts

The PR #1051 containing a bugfix for #1050 was made to `dev` instead of `master` so it wasn't released in `3.0.2`. This PR simply cherry picks that commit into master so it can be released on the next patch release:
Pass multiple connection parameters to runFirstColumn

Port PR #1051 to master

---

packages/graphql/src/classes/Node.ts
packages/graphql/src/schema/make-augmented-schema.ts
packages/graphql/src/schema/resolvers/aggregate.ts
packages/graphql/src/translate/translate-aggregate.ts
packages/ogm/src/generate.ts
packages/ogm/tests/issues/1130.test.ts

Supersedes #1200 
Changes look at the `__typename` field on the generated types over the 'top level type name`, this is because GraphQL Codegen is not preserving the type names. I have raised an issue about that here https://github.com/dotansimha/graphql-code-generator/issues/7714
Some refactors to the aggregation types - centrally storing them in the `Node` class. 
#1130 
Closes: #1130

Fix/use __typename when looking for other types

---

examples/neo-push/client/package.json
examples/neo-push/client/src/tsconfig.json
examples/neo-push/client/webpack.config.js
examples/neo-push/server/package.json
examples/neo-push/server/src/server.ts
yarn.lock

This PR fixes the neo-push server and client. They should now run again locally.
**More importantly**:
There are several Dependabot alerts that should be resolved. For instance:
Upgrade ansi-html to version 0.0.8 or later
Upgrade node-forge to version 1.3.0 or later
It turns out that those two dependencies above are used in the outdated version of webpack-dev-server in the neo-push client. Bumping it gets rid of those two dependencies.

Fix: neo-push client and server

---

docs/modules/ROOT/pages/api-reference/neo4jgraphql.adoc

docs: fix typo in api reference

---

packages/graphql/src/schema/types/scalars/Time.test.ts
packages/graphql/src/schema/types/scalars/Time.ts
packages/graphql/tests/tck/tck-test-files/types/time.test.ts

Updates time regex to support `HH:MM` format, some tests added to ensure valid and invalid formats
Note: Variable `RFC_3339_REGEX` renamed to `TIME_REGEX` to avoid confusion, as the regex does not strictly follow RFC_3339 format.
#1234

Add tests on time parse and update regex

---

packages/graphql/src/translate/create-interface-projection-and-params.ts
packages/graphql/tests/integration/issues/1348.int.test.ts
packages/graphql/tests/tck/tck-test-files/directives/auth/arguments/allow/interface-relationships/implementation-allow.test.ts
packages/graphql/tests/tck/tck-test-files/directives/auth/arguments/allow/interface-relationships/interface-allow.test.ts
packages/graphql/tests/tck/tck-test-files/directives/auth/arguments/where/interface-relationships/implementation-where.test.ts
packages/graphql/tests/tck/tck-test-files/directives/auth/arguments/where/interface-relationships/interface-where.test.ts
packages/graphql/tests/tck/tck-test-files/directives/auth/projection-interface-relationships.test.ts
packages/graphql/tests/tck/tck-test-files/interface-relationships/create/connect.test.ts
packages/graphql/tests/tck/tck-test-files/interface-relationships/create/create.test.ts
packages/graphql/tests/tck/tck-test-files/interface-relationships/read.test.ts
packages/graphql/tests/tck/tck-test-files/interface-relationships/update/create.test.ts
packages/graphql/tests/tck/tck-test-files/issues/1348.test.ts
packages/graphql/tests/tck/tck-test-files/issues/583.test.ts
packages/graphql/tests/tck/tck-test-files/issues/847.test.ts
packages/graphql/tests/tck/tck-test-files/undirected-relationships/undirected-relationships.test.ts

Wrap the subqueries call (The UNIONs) in an additional CALL to prevent altering the original input (the `this` variable).
#1348
Closes:
- #1348

Fix Issue 1348: Missing results when querying interface relationships

---

packages/graphql/src/schema/check-directive-combinations.ts

As it says on the tin!
Reported on Discord.

Prevent `@callback` directive from being used with `@relationship`

---

renovate.json

This was really starting to bug me, so I did some digging... Turns out by extending `config:js-lib`, you are extending `config:base`, which in turn extends `:ignoreModulesAndTests`... [Which ignores `**/examples/**`](https://docs.renovatebot.com/presets-default/#ignoremodulesandtests)! I've now overridden this not to ignore that pattern, so hopefully when this is merged we should start seeing our examples auto-updated.

Get Renovate to update example dependencies (hopefully)

---

packages/graphql/src/schema/get-document.ts

It was reported on Discord that merging of type definitions was failing in certain scenarios, and I wonder if our excessive casting to strings is responsible...

Remove pointless casting in getDocument

---

packages/graphql/src/schema/subscriptions/generate-subscription-types.ts
packages/graphql/tests/e2e/subscriptions/create.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/delete.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/update.e2e.test.ts
packages/graphql/tests/schema/subscriptions.test.ts

Timestamp is missing from subscriptions payload. This PR adds the timestamp from the subscription event

Adds timestamp to subscriptions response

---

packages/graphql-toolbox/src/index.html
packages/graphql-toolbox/src/utils/utils.ts

https://codemirror.net/lib/codemirror.css and https://codemirror.net/addon/hint/show-hint.css are not accessible anymore (404 Error). This implementation is a leftover from the prototype version of the Toolbox.
Instead, we import the css files directly in `packages/graphql-toolbox/src/utils/utils.ts`

Fix: Toolbox - import Codemirror stylesheet

---

docs/modules/ROOT/pages/toolbox.adoc

There was a typo in the sentence around Node.js on the Toolbox page, but I don't think it is necessary at all.

Docs: remove unnecessary requirement from Toolbox page

---

packages/graphql-toolbox/src/modules/TopBar/TopBar.tsx

Removing the `beta` tag in the GraphQL Toolbox.

Feat: Toolbox - remove the beta tag

---

.github/workflows/docs-build.yml
.github/workflows/docs-publish.yml
.github/workflows/ui-stage-build.yml
.github/workflows/ui-stage-publish.yml

Note: This PR is against `master`.
Using the same changes as in https://github.com/neo4j/graphql/pull/1610.
Cleanup PR number usage in docs and UI workflows to follow the commonly used `github.event.pull_request.number`.

Fix: UI and doc publish

---

packages/graphql/tests/utils/is-multi-db-unsupported-error.ts

Continued 5.0 compatibility effort following failure of `supportsMultiDb`.

Remove Neo4jError prefix when checking for multi DB error

---

.changeset/tall-windows-relax.md
packages/graphql/src/translate/where/create-connection-where-and-params.ts
packages/graphql/tests/tck/tck-test-files/issues/1263.test.ts

There was some overly complex code generating the where clause for the `_on` argument - this has been removed which fixed the Cypher issue.
Closes #1263

Fix: remove redundant check against non-existent parameter when querying interface connection

---

.changeset/eight-doors-own.md
packages/graphql/src/classes/Executor.ts

If a default database is not always specified, this will result in a round-trip request to the database for the routing table, which can then lead on to other issues. This PR always specifies "neo4j" as the default database unless overridden.

fix: always specify a default database

---

.changeset/short-ants-return.md
packages/graphql/src/translate/where/create-where-and-params.ts
packages/graphql/tests/integration/issues/1779.int.test.ts
packages/graphql/tests/tck/tck-test-files/advanced-filtering.test.ts
packages/graphql/tests/tck/tck-test-files/directives/node/node-label.test.ts
packages/graphql/tests/tck/tck-test-files/directives/node/node-with-auth.test.ts
packages/graphql/tests/tck/tck-test-files/issues/1628.test.ts
packages/graphql/tests/tck/tck-test-files/issues/1779.test.ts
packages/graphql/tests/tck/tck-test-files/issues/190.test.ts

Reported on Discord, `EXISTS` was being used in a `RETURN` clause where it is not valid.
This PR fixes this by switching to the `listPredicateToSizeFunction` to generate the clause. It's a shame, because we're now only using `EXISTS` in one place, which is the better solution. We need to switch from doing our projections of relationships in the `RETURN` clause itself to get around this.
Closes #1779

fixed: an EXISTS clause is used in a RETURN clause where it is not valid

---

.github/workflows/pull-requests.yml
jest.config.base.js
packages/graphql/global.d.ts
packages/graphql/jest.config.js
packages/graphql/jest.test-setup.js
packages/graphql/package.json
packages/graphql/tsconfig.json
yarn.lock

When asserting the values of arrays, what is currently:
```js
const array = [1, 2, 3]; // assume that we don't know the order here
expect(array).toHaveLength(3);
expect(array).toBe(expect.arrayContaining([3, 2, 1]);
```
Can now become:
```js
const array = [1, 2, 3]; // assume that we don't know the order here
expect(array).toIncludeSameMembers([3, 2, 1]);
```
This also works for nested items, for instance:
```js
expect(o).toEqual({
nestedArray: expect.toIncludeSameMembers([3, 2, 1]),
});
```
This should become our de facto standard for asserting the values of arrays unless we're _100% sure_ of the order, to avoid test flakiness. We should refactor all existing tests.

Add boilerplate needed to use toIncludeSameMembers from jest-extended

---

.changeset/config.json
.github/workflows/changesets-master.yml

A couple of changes which came out of the woodwork as part of the hotfix release:
- The GraphQL Toolbox should be bumped whenever we bump the library - this will lead onto more reliable releases
- A branch should be created from `master` before creating a PR into `dev` following a hotfix release - this will avoid corrupting the commit history of `master`.

Release tweaks following first hotfix

---

packages/graphql/src/schema/resolvers/field/cypher.ts
packages/graphql/src/translate/connection/create-connection-and-params.ts
packages/graphql/src/translate/create-interface-projection-and-params.ts
packages/graphql/src/translate/create-projection-and-params.test.ts
packages/graphql/src/translate/create-projection-and-params.ts
packages/graphql/src/translate/translate-create.ts
packages/graphql/src/translate/translate-read.ts
packages/graphql/src/translate/translate-update.ts

This PR simply moves the `createProjectionAndParams` from an array to an object, to accommodate the extra fields required for subquery projections.
No tests or behaviour modified.

refactor createProjectionAndParam result

---

packages/graphql/src/translate/cypher-builder/utils.test.ts

Adds tests to ensure that unicode `\u0060` is properly escaped for cypher labels

Add unit tests on unicode for escapeLabel

---

.changeset/nice-parrots-kick.md
packages/graphql/src/translate/cypher-builder/CypherBuilder.ts
packages/graphql/src/translate/cypher-builder/functions/PredicateFunctions.ts
packages/graphql/src/translate/where/property-operations/create-relationship-operation.ts
packages/graphql/src/translate/where/property-operations/create-where-property-operation.ts
packages/graphql/tests/performance/graphql/query.graphql
packages/graphql/tests/tck/tck-test-files/advanced-filtering.test.ts

After some performance test, it is clear that using `single()` instead of `size() = 1` improves performance on `_SINGLE` operations for the cases reported in #1937

Performance improvement on _SINGLE operation

---

renovate.json

This should fix the Renovate configuration, by switching the configuration preset to `config:base` and then adding the specifics of `config:js-app` and `config:js-lib` to the packages that need it.
I also removed the label configuration because this is out of date, and we don't really take advantage of it.

Fix Renovate configuration

---

packages/graphql/tests/integration/aggregations/where/edge/int.int.test.ts

This test file was quite flaky when executing the integration tests locally.
The fix is to do what the test subscription indicates: `should return posts where the average of an edge like Int's is LTE than`, note the word `average`.
In a related file for testing the aggregates on nodes this is done correctly, with the `AVERAGE_` string before the operator: https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/integration/aggregations/where/node/int.int.test.ts#L451

fix: test checks the average of integers for the edge aggregate

---

packages/graphql-toolbox/src/modules/HelpDrawer/Resources.tsx

This popped up during the code scanning.
Info:
```
HTML links that open in a new tab or window allow the target page to access the DOM of the origin page using
window.opener unless link type noopener or noreferrer is specified.
```
It's low severity yet easy to fix.

feat: add rel noreferrer to link

---

examples/neo-push/client/src/index.html

This popped up in the code scanning (low severity).
Info:
```
Including a resource from an untrusted source or using an untrusted channel may allow an attacker to include
arbitrary code in the response. When including an external resource (for example, a script element or an iframe element)
on a page, it is important to ensure that the received data is not malicious.
```
Can't find any trace that these stylesheets and the imported `highlight.js` library are still used.

fix: remove unsused script and stylesheets links in neo-push client

---

.github/workflows/lint-github-actions.yml

There is an issue where reviewdog/action-actionlint is running out of memory in the JS heap

Increase reviewdog memory limit to 4096 GB

---

examples/neo-push/server/package.json
package.json
packages/graphql-toolbox/package.json
packages/graphql/package.json
packages/graphql/src/classes/Neo4jGraphQL.ts
packages/graphql/src/classes/utils/asserts-indexes-and-constraints.ts
packages/graphql/tests/integration/directives/fulltext.int.test.ts
packages/graphql/tests/integration/directives/unique.int.test.ts
packages/introspector/package.json
packages/ogm/package.json
packages/plugins/graphql-plugin-subscriptions-amqp/package.json
yarn.lock

There is still one issue left which I am working through, but this PR:
- Allows the `neo4j-driver@5.0.0` to be used as a peer dependency
- Generates `CREATE CONSTRAINT` calls dynamically based on database version
- Removes some use of index functions from tests

Further fixes for 5.0.0 compatibility

---

.changeset/proud-houses-love.md
docs/modules/ROOT/pages/filtering.adoc
docs/modules/ROOT/pages/subscriptions/filtering.adoc
packages/graphql/src/schema/resolvers/subscriptions/update-diff-filter.ts
packages/graphql/src/schema/resolvers/subscriptions/utils/compare-properties.ts
packages/graphql/src/schema/subscriptions/generate-subscription-where-type.ts
packages/graphql/src/schema/to-compose.ts
packages/graphql/src/utils/utils.ts
packages/graphql/tests/e2e/subscriptions/create.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/delete.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/filtering/create-array-filters.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/filtering/create-number-filters.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/filtering/create-string-filters.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/filtering/create.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/filtering/delete-array-filters.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/filtering/delete-number-filters.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/filtering/delete-string-filters.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/filtering/delete.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/filtering/update-array-filters.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/filtering/update-number-filters.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/filtering/update-string-filters.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/filtering/update.e2e.test.ts
packages/graphql/tests/e2e/subscriptions/update.e2e.test.ts
packages/graphql/tests/schema/subscriptions.test.ts

Allows for combining filters using AND/ OR for subscriptions.

Implement and/or filters on subscriptions

---

.changeset/config.json

An update to changesets means that private packages can now be tagged - this should fully automate the Toolbox deployment flow! 🎉 
Depends on dependency update in #2163.

Update changesets config.json

---

packages/graphql/tests/utils/clean-nodes.ts
packages/graphql/tests/utils/run-cypher.ts

The helper function for tests `cleanNodes` was not working as expected. The cypher has been fixed and is now using CypherBuilder

Fix clean nodes

---

.changeset/smooth-panthers-nail.md
packages/graphql/src/translate/projection/subquery/translate-cypher-directive-projection.ts
packages/graphql/tests/integration/issues/2189.int.test.ts
packages/graphql/tests/tck/directives/cypher.test.ts
packages/graphql/tests/tck/issues/1364.test.ts
packages/graphql/tests/tck/issues/1528.test.ts
packages/graphql/tests/tck/issues/1760.test.ts
packages/graphql/tests/tck/issues/2100.test.ts
packages/graphql/tests/tck/issues/387.test.ts
packages/graphql/tests/tck/sort.test.ts

This PR fixes #2189 , introduced in 3.9.0 in which the nodes with empty `@cypher` fields are filtered out.

2189 cypher directive seems to force query to omit results with missing fields

---

.github/workflows/docs-publish.yml
.github/workflows/ui-stage-publish.yml
.github/workflows/yarn-update.yml

"set-output" was deprecated as shown in our failing actions linting workflows, so this PR replaces it with the new suggested variable assignment method.

Replace deprecated "set-output" workflow command

---

packages/graphql-toolbox/package.json
packages/graphql-toolbox/src/modules/Main/Main.tsx
packages/graphql-toolbox/src/modules/TopBar/TopBar.tsx
packages/graphql-toolbox/tailwind.config.js
yarn.lock

This PR contains:
- A clickable banner to open a new tab with the GraphQLaaS interest form
- Re-use the former "GraphQLaaS interest" button to instead redirect users to the Canny page in a new tab to provide feedback

feat: Toolbox banner for GraphQLaaS interest redirect

---

docs/contributing/DEVELOPING.md
packages/graphql/tests/performance/graphql/batch-create/batch-create-interface.graphql
packages/graphql/tests/performance/performance.ts
packages/graphql/tests/performance/schema-performance.ts

Adds performance tests on `getSchema` (i.e. server startup) by running `yarn performance --schema`

Add schema generation benchmark

---

.changeset/eighty-apes-knock.md
packages/graphql-toolbox/src/contexts/appsettings.tsx

> **Note**
> 
On load of the application, if `LOCAL_STATE_ENABLE_PRODUCT_USAGE_TRACKING` is not set in the web browser local storage, set it to `true`. This ensures product usage tracking is turned on properly on load of the application.
NOTE: The user can at any point opt out of product usage tracking!
> **Note**
>

fix: Toolbox default product usage tracking state

---

.github/workflows/performance-tests-comment.yml

Pass the performanceReport file directly to the path parameter of the sticky-pull-request-comment action.

Pass performanceReport with path parameter

---

.github/workflows/changesets-master.yml

For every merge into `master` (on release from `dev`), we are creating a branch due to a missing conditional. This fixes that issue. I will tidy the branches.

Add missing conditional which is causing excess branches to be created

---

examples/neo-place/package.json
examples/subscriptions/apollo_rabbitmq/package.json
package.json
yarn.lock

This should stop Renovate trying to bump internal dependencies for these in future.

Add missing examples to workspace

---

.github/workflows/reusable-api-library-tests.yml
.github/workflows/reusable-integration-tests-on-prem.yml
.github/workflows/reusable-subscriptions-plugin-amqp-e2e-test.yml

Our pull request tests which rely on a 4.x Neo4j DB fail due to an inability to connect to the Neo4j DB.
Trying to reset to an older version for 4.3 and 4.4 to see if the problem persists.

fix: set neo4j-version in GHA to older version for 4.x

---

.changeset/lovely-mugs-matter.md
packages/graphql/src/schema/get-nodes.ts
packages/graphql/tests/integration/issues/2560.int.test.ts

> **Note**
> 
The `resolvers` input for the `Neo4jGraphQL` class accepts both `IResolvers` and `IResolvers[]`. With this PR we add support for the latter.
> **Note**
>
> **Note**
>
>  
Closes #2560 

fix: custom resolvers as array

---

.github/workflows/reusable-integration-tests-on-prem-nightly.yml
.github/workflows/reusable-integration-tests-on-prem.yml

With this PR we test if the library passes integration tests with Node.js version 19.
At the moment we only test it on GHA against the latest node.js lts (v18.X)
For now, we only check it for the nightly build.

feat: GHA matrix with node versions for nightly build

---

.changeset/odd-tables-lie.md
packages/graphql/src/translate/field-aggregations/create-field-aggregation.ts
packages/graphql/tests/integration/issues/2669.int.test.ts
packages/graphql/tests/tck/aggregations/field-level-aggregations/field-level-aggregations-alias.test.ts

> **Note**
> 
Aliases from GraphQL fields to database relationship properties were not being translated in aggregations.
> **Note**
>
> **Note**
>
>  
Closes #2669

Fix Cypher translation for aliased database relationship properties

---

.github/workflows/reusable-api-library-tests.yml
.github/workflows/reusable-integration-tests-on-prem.yml
.github/workflows/reusable-subscriptions-plugin-amqp-e2e-test.yml

Reverts neo4j/graphql#2621
From the APOC lib maintenance team (cypher surface): `This has now been fixed, and tests have been added to make sure it won't happen again`

Revert "fix: set neo4j-version in GHA to older version for 4.x"

---

.github/workflows/dev.yml
.github/workflows/pull-requests.yml
.github/workflows/reusable-api-library-tests.yml
.github/workflows/reusable-integration-tests-on-prem-nightly.yml
.github/workflows/reusable-integration-tests-on-prem.yml
.github/workflows/reusable-unit-tests.yml

Disable upload to CodeCov for nightly builds of the `dev` branch due to an increasing amount of `Too many uploads to the commit` error messages of `dev` nightly builds. It's disabled only for the scheduled nightly builds.

boyscouting: disable CodeCov upload for dev nightly build

---

.github/workflows/reusable-toolbox-tests.yml

The E2E tests for the Toolbox fail due to connectivity issues when installing Playwright (the test runner).
See for instance: https://github.com/neo4j/graphql/actions/runs/3878819827/jobs/6680638507#step:6:644 
This workaround should fix this.
It introduces a bit of a delay (ca 2 mins) due to the `apt-spy2 check` command.

fix: Toolbox E2E tests, connectivty issues 

---

packages/graphql/tests/integration/issues/2709.int.test.ts

> **Note**
> 
In https://github.com/neo4j/graphql/pull/2715 I missed using `expect.toIncludeSameMembers()` to check the content of the response array. The "hard coded" order in a response (array) can cause flakiness in the integration tests.
> **Note**
>

fix: use expect.toIncludeSameMembers to check array content

---

packages/graphql/src/translate/create-connect-and-params.test.ts
packages/graphql/src/translate/create-connect-and-params.ts
packages/graphql/tests/tck/directives/interface-relationships/update/connect.test.ts
packages/graphql/tests/tck/operations/connect.test.ts

This fixes a minor bug introduced by the `overwrite` implementation. The condition has been widened so that it matches the `overwrite=false` case, but passes the  related `relationshipFieldNotOverwritable` field for all cases.

only pass relationship field if overwrite set to false

---

.changeset/gorgeous-ways-refuse.md
packages/graphql/src/translate/projection/subquery/translate-cypher-directive-projection.ts
packages/graphql/tests/integration/issues/2766.int.test.ts
packages/graphql/tests/tck/directives/cypher.test.ts

Fix reusing the same $params in the `@cypher` fields on nested fields
Fixes #2766

Fix duplicate parameters in nested cypher

---

packages/graphql/src/translate/create-aggregate-where-and-params.ts
packages/graphql/src/translate/where/create-where-predicate.ts
packages/graphql/src/translate/where/property-operations/create-connection-operation.ts
packages/graphql/tests/integration/connections/filtering.int.test.ts

Fix a bug introduced with the `NOT` operator PR, logical filters inside a connection field was treated as an array, but the `NOT` operator value is an object. 
Complexity: Literally one change

fix connection where with logical operator

---

.github/workflows/docs-publish.yml
.github/workflows/performance-tests-comment.yml
.github/workflows/ui-stage-publish.yml

> **Note**
> 
Our various sticky comment calls were colliding - hence why we've been missing docs and Toolbox publish messages lately - they were being overridden by the performance report! 🤦 
> **Note**
>

Add header to sticky comments, prevents overwrite

---

.changeset/four-insects-beam.md
packages/cypher-builder/src/references/PropertyRef.test.ts
packages/cypher-builder/src/references/PropertyRef.ts
packages/cypher-builder/src/references/Reference.ts

Add support for syntax such as `this["prop"]` in cypher builder

Add support for square bracket properties in cypher builder

---

.changeset/config.json

> **Note**
> 
If you check the current changesets PR, it wants to bump the AMQP Subscriptions plugin to 3.0.0 - we obviously don't want to do that! We have already accidentally released 2.0.0 (please check the proposed changelogs before merging!).
This is due to https://github.com/changesets/changesets/blob/main/docs/decisions.md#the-versioning-of-peer-dependencies
This adds an experimental option to disable this behaviour, but we will need to keep an eye on this.
> **Note**
>

Add experimental option to disable bump on peer dependency bump

---

.github/workflows/pull-requests.yml
.github/workflows/reusable-package-tests.yml

The latest opened PRs are failing due to errors in the reviewdog action-eslint and the package-tests Github actions.
See for the reviewdog eslint-action: https://github.com/neo4j/graphql/actions/runs/4139641732/jobs/7161364297
And also for the package-tests: https://github.com/neo4j/graphql/actions/runs/4139641732/jobs/7161375522
The execution fails on node.js v18.14.0. Setting the node.js version to v18.13.0 in these two Github actions resolves this.
Info on the Github action `actions/setup-node@v3`:
```
node: v18.13.0
npm: 8.19.3
yarn: 3.4.1
```
```
node: v18.14.0
npm: 9.3.1
yarn: 3.4.1
```
Note the large difference of `npm` versions.
It could be likely that the errors are due to this increase in the npm version.

fix: set node.js version for reviewdog-eslint&package-tests GHA to v18.13.0

---

.changeset/fast-carpets-grow.md
packages/graphql/src/translate/batch-create/parser.ts
packages/graphql/tests/integration/issues/2889.int.test.ts

> **Note**
> 
When generating Cypher for an `UNWIND CREATE`, input should have been checked for enums as well as scalars.
> **Note**
>
> **Note**
>
>  
Closes #2889

Check for enums as well as scalars when doing UNWIND CREATE

---

.eslintrc.js

> **Note**
> 
The current combined Prettier+ESLint combination does not add trailing commas for multi-line statements as Prettier would like. This adds the comma-dangle rule to our .eslintrc which will fix this behaviour.
> **Note**
>

Add comma-dangle to .eslintrc

---

LICENSE.txt
package.json

Adding the `LICENSE.txt` file to the repo root and adding `license` to the root `package.json`.
Thank you @cliffordfajardo for pointing this out in https://github.com/neo4j/graphql/pull/2956

feat: license information at the root of this project

---

.changeset/chilled-zebras-vanish.md
packages/graphql/src/translate/create-projection-and-params.ts
packages/graphql/tests/integration/issues/2982.int.test.ts
packages/graphql/tests/integration/issues/inline-fragment-aggregate.int.test.ts

This PR fixes a syntax error that occurred when querying the count aggregate field inside an inline fragment. The problem here was that the code responsible for sanitizing nested projections in inline fragments would remove all opening and closing brackets in the nested query, which would result in invalid syntax when the nested query contained more nested fields:
`{ .id } -> .id // works`  
`{ fieldAggregate: { count: var }} -> fieldAggregate:  count: var // syntax error`
The offending regex here was `/{|)/gm`. I've looked through all the test cases triggering this code, and it seems there is never more than 1 set of brackets in all other cases, and never any multiline strings. I've adjusted the replace regexes to first remove any newlines, and then clear any opening brackets and closing …

Fix count aggregate field in inline fragments

---

.changeset/tame-zoos-turn.md
packages/graphql/src/translate/create-update-and-params.ts
packages/graphql/src/translate/translate-update.ts
packages/graphql/tests/tck/issues/894.test.ts
packages/graphql/tests/tck/operations/update.test.ts
packages/graphql/tests/tck/rfcs/rfc-003.test.ts

> **Note**
> 
Enforces the following order for nested update operations:
1. `delete`
2. `disconnect`
3. `update`
4. `connect` (and `connectOrCreate`)
5. `create`
This was discussed in a workshop several weeks ago now. This will prevent items in a nested create or connect being deleted by a proceeding nested delete.
> **Note**
>

Fix order of operations for nested update

---

.changeset/curly-scissors-help.md
docs/modules/ROOT/pages/guides/v4-migration/index.adoc
docs/modules/ROOT/pages/type-definitions/database-mapping.adoc
packages/graphql/src/classes/utils/asserts-indexes-and-constraints.ts
packages/graphql/src/schema/get-alias-meta.ts
packages/graphql/src/schema/get-obj-field-meta.ts
packages/graphql/src/types.ts
packages/graphql/src/utils/map-to-db-property.ts
packages/graphql/tests/tck/aggregations/alias-directive.test.ts
packages/graphql/tests/tck/issues/1131.test.ts

This PR adds escaping to property alias strings.
There is still a need for an unescaped version of the property alias string so this is added as a new property `dbPropertyNameUnescaped` on the `BaseField` type.
Low

Escape property aliases

---

.changeset/khaki-experts-decide.md
docs/modules/ROOT/pages/guides/v4-migration/index.adoc
packages/graphql/src/classes/Neo4jGraphQL.ts
packages/graphql/src/schema/validation/validate-custom-resolver-requires.ts
packages/graphql/src/schema/validation/validate-document.test.ts
packages/graphql/src/schema/validation/validate-document.ts
packages/graphql/src/schema/validation/validate-duplicate-relationship-fields.test.ts
packages/graphql/src/schema/validation/validate-duplicate-relationship-fields.ts
packages/graphql/src/schema/validation/validate-schema-customizations.ts
packages/graphql/src/types.ts
packages/graphql/tests/integration/config-options/startup-validation.int.test.ts
packages/graphql/tests/schema/rfcs/rfc-003.test.ts

This PR introduces validation to detect cases where types have duplicate relationship fields. 
A duplicate relationship field is when multiple relationship fields are defined on the same type with the same relationship type and the same direction. 
Here's an example of duplicate relationship fields:
```graphql
type Team {
player1: Person! @relationship(type: "PLAYS_IN", direction: IN)
player2: Person! @relationship(type: "PLAYS_IN", direction: IN)
backupPlayers: [Person!]! @relationship(type: "PLAYS_IN", direction: IN)
}
type Person {
teams: [Team!]! @relationship(type: "PLAYS_IN", direction: OUT)
}
```
To allow disabling the checks for duplicate relationship fields, the `noDuplicateRelationshipFields` config option has been added.
Medium

Restrict multiple relationship fields with same type

---

.changeset/hot-carrots-reflect.md
docs/modules/ROOT/pages/api-reference/neo4jgraphql.adoc
docs/modules/ROOT/pages/filtering.adoc
packages/graphql-toolbox/src/modules/SchemaView/SchemaView.tsx
packages/graphql/src/classes/Neo4jGraphQL.ts
packages/graphql/src/schema/get-where-fields.ts
packages/graphql/src/schema/make-augmented-schema.test.ts
packages/graphql/src/types/index.ts
packages/graphql/tests/integration/filtering/advanced-filtering.int.test.ts
packages/graphql/tests/tck/advanced-filtering.test.ts
packages/graphql/tests/tck/connections/filtering/node/string.test.ts
packages/graphql/tests/tck/connections/filtering/relationship/string.test.ts
packages/graphql/tests/tck/directives/coalesce.test.ts

This PR deprecates the `enableRegex` config option in favour of a new `MATCHES` option added to `features.filters`.
The `_MATCHES` comparator can now be enabled separately for `String` or `ID`, as follows:
```ts
const features = {
filters: {
String: {
MATCHES: true,
},
ID: {
MATCHES: true,
}
}
};
const neoSchema = new Neo4jGraphQL({ features, typeDefs, driver });
```
Complexity:
Medium

Add MATCHES features.filters settings to deprecate enableRegex

---

.changeset/shy-moles-invite.md
packages/graphql/src/classes/Neo4jGraphQL.ts
packages/graphql/src/schema/make-augmented-schema.ts
packages/graphql/src/schema/resolvers/wrapper.ts
packages/graphql/tests/integration/issues/1756.int.test.ts
packages/graphql/tests/tck/issues/1756.test.ts

This PR remove `config.callbacks` as it has been deprecated and replaced with features.populatedBy.callbacks.
Low

Remove config.callbacks

---

packages/graphql/src/translate/create-projection-and-params.ts
packages/graphql/src/translate/projection/subquery/translate-cypher-directive-projection.ts

> **Note**
> 
Removes `cypherSortFields` from projection return... This appears to be completely unused, and no tests fail as a result of removing this. Will make tidying up for authorization easier.
> **Note**
>

Remove cypherSortFields

---

.changeset/shaggy-dingos-melt.md
packages/cypher-builder/src/Cypher.ts
packages/cypher-builder/src/expressions/operations/math.test.ts
packages/cypher-builder/src/expressions/operations/math.ts

Add  `divide`, `multiply`, `remainder` and `pow` to the Math Operators.

Add divide, multiply, remainder and pow to the Math Operators.

---

.changeset/witty-roses-deliver.md
docs/modules/ROOT/pages/auth/setup.adoc
packages/graphql/tests/integration/directives/auth/jwks-endpoint.int.test.ts
packages/plugins/graphql-plugin-auth/src/Neo4jGraphQLAuthJWKSPlugin.ts
packages/plugins/graphql-plugin-auth/src/Neo4jGraphQLAuthJWTPlugin.test.ts
packages/plugins/graphql-plugin-auth/src/Neo4jGraphQLAuthJWTPlugin.ts

> **Note**
> 
Add optional constructor arguments to the `Neo4jGraphQLAuthJWTPlugin` and the `Neo4jGraphQLAuthJWKSPlugin` to check the `iss` and the `aud` claim in a JWT token on token verification.
> **Note**
>

feat: Auth plugin, optional iss and aud JWT claim check

---

.changeset/early-jars-punch.md
packages/graphql-toolbox/src/index.css

> **Note**
> 
The opacity and the color of the text selection (select text for instance with the mouse) in the CodeMirror editors got overwritten when introducing the GraphiQL v2 Docs component. This PR addresses this.
> **Note**
>

fix: Toolbox, Codemirror text selection

---

.github/workflows/reusable-toolbox-tests.yml
packages/graphql-toolbox/.env.example
packages/graphql-toolbox/package.json
packages/graphql-toolbox/playwright.config.ts
packages/graphql-toolbox/tests/drawer.test.ts
packages/graphql-toolbox/tests/introspection.test.ts
packages/graphql-toolbox/tests/introspectionprompt.test.ts
packages/graphql-toolbox/tests/login.test.ts
packages/graphql-toolbox/tests/settings.test.ts
packages/graphql-toolbox/tests/urlqueryparameters.test.ts
packages/graphql-toolbox/tests/workflow.test.ts
yarn.lock

> **Note**
> 
This PR:
- Updates to the Toolbox e2e-test GHA workflow:
- Store artifacts of the playwright report when the test run fails.
- One additional step to build the Toolbox prior to the playwright E2E test execution. This helps to fail fast in case there is a build error that would prevent starting up the Toolbox (called webserver in the playwright config) for the playwright tests.
- For localhost execution of the Toolbox E2E tests:
- Add `dotenv` to pick up the env variables containing the credentials to your local database.
> **Note**
>

boyscouting: Toolbox E2E test tweaks

---

.changeset/fluffy-pillows-flow.md
packages/graphql/src/classes/Node.ts
packages/graphql/src/schema/augment/fulltext.ts
packages/graphql/src/schema/get-nodes.ts
packages/graphql/src/schema/make-augmented-schema.ts
packages/graphql/tests/e2e/federation/entities-basics.e2e.test.ts
packages/graphql/tests/schema/federation.test.ts
packages/graphql/tests/utils/builders/node-builder.ts

Previously, `federationResolvable` was implemented to prevent queries and mutations for a type from being generated when resolvable is set to false. This was determined to be the wrong action to take, so this PR removes this logic.
Low

Remove federationResolvable

---

.changeset/metal-crews-rule.md
packages/graphql-toolbox/src/index.css

> **Note**
> 
The red wiggled line which indicates (linting) errors in the editors disappeared after introducing the GraphiQL v2 component for the Schema Docs.
This is just a temporary measure, as soon as the editors are replaced with GraphiQL v2 components this should not be an issue anymore.
> **Note**
>

fix: Toolbox, show lint mark in editors

---

.changeset/curvy-boxes-cry.md
packages/graphql/src/classes/Executor.ts

Following the flame graph analysis in #3304, by avoiding the operation `print` in the executor, we can avoid another "hot code" that is being executed with each query.
The previous behaviours of printing the AST is still a fallback in case `source.query` is not available.
The following measurements where taken to validate this fix, with 1000 Virtual Users sending requests for 1:45. Two runs were done and the average taken per measure:
| query                   | server | requestsBefore | RequestAfter   |
| ----------------------- | ------ | -------------- | -------------- |
| SimpleQuery             | Apollo | 186447         | 202900 (+8.8%) |
| HighComplexityWithLimit | Apollo | 19523          | 20442 (+4.7%)  |
| SimpleQuery             | Yoga   | 226092         | 247651 (+9.5%) |
In …

Optimise query source metadata in executor

---

.changeset/cool-cooks-rhyme.md
packages/graphql/src/translate/translate-update.ts
packages/graphql/tests/integration/issues/3251.int.test.ts
packages/graphql/tests/tck/directives/auth/arguments/allow/allow.test.ts
packages/graphql/tests/tck/directives/auth/arguments/allow/inherited.test.ts
packages/graphql/tests/tck/directives/auth/arguments/allow/interface-relationships/interface-allow.test.ts
packages/graphql/tests/tck/directives/auth/arguments/roles/roles.test.ts
packages/graphql/tests/tck/directives/auth/arguments/where/interface-relationships/implementation-where.test.ts
packages/graphql/tests/tck/directives/auth/arguments/where/interface-relationships/interface-where.test.ts
packages/graphql/tests/tck/issues/324.test.ts
packages/graphql/tests/tck/issues/3251.test.ts
packages/graphql/tests/tck/rfcs/rfc-003.test.ts

> **Note**
> 
The generation of relationship validation string was being skipped if a nested update was within the input.
This swaps this logic around, skipping the relationship validation at the nested level, instead generating it at the root.
> **Note**
>
> **Note**
>
>  
Closes #3251

Fix relationship validation for update Mutations with multiple operations

---

.github/workflows/performance-tests.yml
.github/workflows/reusable-api-library-tests.yml
.github/workflows/reusable-integration-tests-on-prem.yml
.github/workflows/reusable-subscriptions-plugin-amqp-e2e-test.yml
.github/workflows/reusable-toolbox-tests.yml

> **Note**
> 
Replacing `NEO4J_PLUGINS: apoc-core` with `NEO4J_PLUGINS: apoc` for the GHA services that use Neo4j 4.4 and 5.X. 
Reason: Neo4j 5.X is failing due to `“apoc-core” is not a known Neo4j plugin`.
This means that for Neo4j 4.4, the apoc plugin will be fetched remotely. For Neo4j 5.X, the bundled apoc plugin will be used.
Connected to https://github.com/neo4j/graphql/pull/3345

fix: broken GHA with neo4j 5.X

---

.changeset/fuzzy-fishes-hear.md
packages/graphql/src/classes/GraphElement.ts
packages/graphql/src/translate/projection/subquery/add-sort-and-limit-to-clause.ts
packages/graphql/src/translate/translate-read.ts
packages/graphql/tests/integration/issues/3394.int.test.ts
packages/graphql/tests/tck/issues/3394.test.ts

When sorting, we are using the options argument directly. This PR transforms the given fields to the DbFieldNames when needed to properly take `@alias` into account.
This PR adds a method `getFields` in Node which is not efficient and should be refactored into the SchemaModel
Closes #3394

3394 ordering not taking alias into account

---

packages/graphql/src/graphql/directives/index.ts
packages/graphql/src/graphql/directives/settable.ts
packages/graphql/src/schema/create-relationship-fields/create-relationship-fields.ts
packages/graphql/src/schema/get-obj-field-meta.ts
packages/graphql/src/schema/resolvers/subscriptions/where.test.ts
packages/graphql/src/schema/to-compose.ts
packages/graphql/src/translate/create-auth-and-params.test.ts
packages/graphql/src/translate/create-connect-and-params.test.ts
packages/graphql/src/translate/create-create-and-params.test.ts
packages/graphql/src/translate/create-disconnect-and-params.test.ts
packages/graphql/src/translate/create-projection-and-params.test.ts
packages/graphql/src/translate/create-update-and-params.test.ts
packages/graphql/src/translate/projection/elements/create-relationship-property-element.test.ts
packages/graphql/src/types/index.ts
packages/graphql/tests/schema/directives/settable.test.ts
packages/graphql/tests/utils/builders/relation-field-builder.ts

> This PR depends on #3403 
Adds `@settable` directive defined in https://github.com/neo4j/graphql/discussions/3263
This directive has the following options:
* onCreate
* onUpdate
Setting these values will disable the generation of the GraphQL input fields for create operations and update operations
Complexity: Medium

Settable directive

---

packages/graphql/package.json
packages/graphql/tests/tck/connections/connect-or-create/connect-or-create-alias.test.ts
yarn.lock

Update `@neo4j/cypher-builder` to `0.5.3` to fix an escaping issue that was causing the tests to fail

Fix property escaping in MERGE operation

---

.changeset/quick-items-laugh.md
packages/ogm/src/generate.test.ts
packages/ogm/src/generate.ts

This PR opts to keep the casing generated by the library when using GraphQL Codegen.
Closes #3539

Preserve library casing in OGM

---

packages/graphql/tests/tck/issues/2789.test.ts

Simply adds a TCK test for #2789 so we can close it as resolved by the new authorization directives.
Closes #2789

Add test satisfying that #2789 is resolved

---

.changeset/new-comics-retire.md
docs/modules/ROOT/pages/migration/v4-migration/index.adoc
docs/modules/ROOT/pages/troubleshooting.adoc
packages/graphql-toolbox/src/modules/EditorView/EditorView.tsx
packages/graphql-toolbox/src/modules/SchemaView/SchemaView.tsx
packages/graphql/src/classes/Neo4jGraphQL.ts

Programmatic toggling of debug logging is done using:
```gql
const neoSchema = new Neo4jGraphQL({
typeDefs,
driver,
debug: true,
});
```
This further reduces the `config` object, which honestly I think we should just be rid of.

Simplify the programmatic toggle for debug logging

---

.changeset/moody-crews-march.md
packages/graphql/src/index.ts
packages/ogm/src/types.ts

As part of cleanup towards 4.0.0, remove OGM dependency on library exports.

Remove unused exports now defined in OGM

---

packages/graphql/src/schema-model/generate-model.ts
packages/graphql/src/schema-model/relationship/Relationship.ts
packages/graphql/src/translate/queryAST/ast/fields/OperationField.ts
packages/graphql/src/translate/queryAST/ast/filters/Filter.ts
packages/graphql/src/translate/queryAST/ast/filters/LogicalFilter.ts
packages/graphql/src/translate/queryAST/ast/filters/aggregation/AggregationFilter.ts
packages/graphql/src/translate/queryAST/ast/filters/aggregation/AggregationPropertyFilter.ts
packages/graphql/src/translate/queryAST/ast/filters/aggregation/CountFilter.ts
packages/graphql/src/translate/queryAST/ast/filters/property-filters/PropertyFilter.ts
packages/graphql/src/translate/queryAST/ast/operations/AggregationOperation.ts
packages/graphql/src/translate/queryAST/ast/operations/ReadOperation.ts
packages/graphql/src/translate/queryAST/factory/FilterFactory.ts
packages/graphql/src/translate/queryAST/factory/parsers/parse-where-field.ts
packages/graphql/src/utils/utils.ts
packages/graphql/tests/tck/aggregations/where/composite.test.ts

This PR depends on #3737 
Add `head` on relationship queries that are not arrays
Before:
Test Suites: 102 failed, 135 passed, 237 total
Tests:       282 failed, 968 passed, 1250 total
After:
Test Suites: 101 failed, 136 passed, 237 total
Tests:       277 failed, 973 passed, 1250 total

Is array relationships

---

.changeset/tender-rats-reflect.md
packages/graphql-toolbox/src/modules/EditorView/utils.ts
packages/graphql-toolbox/src/modules/SchemaView/SchemaView.tsx

According to https://codemirror.net/docs/migration/ using .toString() on editorView.state.doc is the preferred method to get the document as a string.
Low

Toolbox: Ensure no additional commas are added to the editor value

---

README.md

This repository adds a link to the [Introduction to Neo4j & GraphQL on GraphAcademy](https://graphacademy.neo4j.com/courses/graphql-basics/?ref=graphql).

Add link to Introduction to Neo4j & GraphQL on GraphAcademy

---

.changeset/funny-items-drive.md
packages/ogm/src/classes/Model.ts

A import of `@neo4j/graphql/src` has snuck into the OGM, preventing it's use.
To be merged urgently for immediate release.

Fix non-relative import in the OGM

---

.changeset/yellow-humans-notice.md
packages/graphql/src/classes/Executor.ts
packages/graphql/src/schema/resolvers/composition/wrap-query-and-mutation.ts
packages/graphql/src/types/neo4j-graphql-context.ts

The context field `transactionMetadata` can be used to pass through arbitrary information into the database transaction metadata.

Feature: pass through transaction metadata

---

packages/graphql/src/schema-model/generate-model.ts
packages/graphql/src/schema-model/parser/annotations-parser/custom-resolver-annotation.ts
packages/graphql/src/schema-model/parser/annotations-parser/filterable-annotation.ts
packages/graphql/src/schema-model/parser/annotations-parser/full-text-annotation.ts
packages/graphql/src/schema-model/parser/annotations-parser/jwt-claim-annotation.ts
packages/graphql/src/schema-model/parser/annotations-parser/limit-annotation.ts
packages/graphql/src/schema-model/parser/annotations-parser/plural-annotation.ts
packages/graphql/src/schema-model/parser/annotations-parser/populated-by-annotation.ts
packages/graphql/src/schema-model/parser/annotations-parser/query-annotation.ts
packages/graphql/src/schema-model/parser/annotations-parser/selectable-annotation.ts
packages/graphql/src/schema-model/parser/annotations-parser/settable-annotation.ts
packages/graphql/src/schema-model/parser/annotations-parser/subscription-annotation.ts
packages/graphql/src/schema-model/parser/annotations-parser/timestamp-annotation.ts
packages/graphql/src/schema-model/parser/annotations-parser/unique-annotation.ts
packages/graphql/src/schema-model/parser/parse-arguments.ts
packages/graphql/src/schema-model/parser/parse-attribute.ts
packages/graphql/src/schema/parse-mutation-directive.ts
packages/graphql/src/schema/parse-query-directive.ts
packages/graphql/src/schema/parse-subscription-directive.ts

Adds a generic type parameter to the parseArguments function and uses it in place of many cases of type assertions.
Low

Add generic types to parseArguments

---

packages/graphql/src/translate/queryAST/ast/QueryASTContext.ts
packages/graphql/src/translate/queryAST/ast/fields/attribute-fields/CypherAttributeField.ts
packages/graphql/src/translate/queryAST/ast/filters/ConnectionFilter.ts
packages/graphql/src/translate/queryAST/ast/filters/RelationshipFilter.ts
packages/graphql/src/translate/queryAST/ast/operations/AggregationOperation.ts
packages/graphql/src/translate/queryAST/ast/operations/ConnectionReadOperation.ts
packages/graphql/src/translate/queryAST/ast/operations/ReadOperation.ts
packages/graphql/src/translate/queryAST/ast/sort/CypherPropertySort.ts
packages/graphql/src/translate/queryAST/ast/sort/Sort.ts
packages/graphql/src/translate/queryAST/factory/SortAndPaginationFactory.ts
packages/graphql/src/translate/queryAST/utils/create-comparison-operator.ts
packages/graphql/src/translate/queryAST/utils/create-cypher-subquery.ts
packages/graphql/tests/tck/issues/3394.test.ts
packages/graphql/tests/tck/sort.test.ts

Fix sort translation logic for cypher fields in the new translation layer
This PR also includes the concept of "Scope" into the queryASTContext to share variables across different nodes from the operationTree
```
Test Suites: 52 failed, 186 passed, 238 total
Tests:       135 failed, 1145 passed, 1280 total
```

Fix cypher with sort

---

packages/graphql/src/translate/queryAST/ast/fields/attribute-fields/CypherAttributeField.ts
packages/graphql/src/translate/queryAST/factory/FieldFactory.ts
packages/graphql/src/translate/queryAST/utils/create-cypher-subquery.ts

Support arguments used in `@cypher` fields.
Fix the following tests:
-  'Cypher directive Nested Connection',
- 'Cypher directive Nested directive',
-  'Cypher directive Nested directive with params',
- 'Cypher directive Super Nested directive',
- 'Cypher directive Top level cypher should query field custom query and return relationship data with given columnName',
- 'https://github.com/neo4j/graphql/issues/2100 query nested relations under a root connection field'

Support argument on cypher fields

---

packages/graphql/src/schema-model/parser/parse-annotation.ts

RelayIDAnnotation is missing from parse-annotation so this PR adds it.
Low

Add RelayIDAnnotation to parse-annotation

---

packages/graphql/src/translate/queryAST/ast/QueryAST.ts
packages/graphql/src/translate/queryAST/ast/operations/ReadOperation.ts
packages/graphql/src/translate/queryAST/ast/operations/interfaces/InterfaceReadOperation.ts
packages/graphql/src/translate/queryAST/ast/operations/interfaces/InterfaceReadPartial.ts
packages/graphql/src/translate/queryAST/factory/OperationFactory.ts
packages/graphql/src/translate/queryAST/factory/QueryASTFactory.ts
packages/graphql/src/translate/queryAST/utils/get-concrete-entities.ts
packages/graphql/tests/tck/directives/authorization/arguments/roles-where.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/where/interface-relationships/implementation-where.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/where/where.test.ts
packages/graphql/tests/tck/directives/authorization/projection-connection-union.test.ts
packages/graphql/tests/tck/directives/authorization/projection-interface-relationships.test.ts
packages/graphql/tests/tck/directives/customResolver.test.ts
packages/graphql/tests/tck/issues/1150.test.ts
packages/graphql/tests/tck/issues/1348.test.ts
packages/graphql/tests/tck/issues/1535.test.ts
packages/graphql/tests/tck/issues/1536.test.ts
packages/graphql/tests/tck/issues/583.test.ts
packages/graphql/tests/tck/issues/847.test.ts
packages/graphql/tests/tck/undirected-relationships/undirected-relationships.test.ts

This PR implements interfaces for read operations and updates several tck tests:
```
'#583 > Should replicate issue and return correct cypher',
'@customResolver directive > Require fields on nested interfaces > should not over fetch when all required fields are manually selected',
'@customResolver directive > Require fields on nested unions > should not over fetch when all required fields are manually selected',
'Auth projections for interface relationship fields > Simple Interface Relationship Query for protected type',
'Cypher Auth Projection On Connections On Unions > Two connection',
'Cypher Auth Where > Read Union Using Connection + User Defined Where',
'Cypher Auth Where > Read interface relationship Using Connection',
'Cypher Auth Where > Read …
```

Interfaces translation layer

---

packages/graphql/src/translate/queryAST/ast/operations/ReadOperation.ts
packages/graphql/src/translate/queryAST/ast/pagination/Pagination.ts
packages/graphql/src/translate/queryAST/factory/OperationFactory.ts
packages/graphql/tests/tck/alias.test.ts
packages/graphql/tests/tck/issues/2267.test.ts

A few extra tests fixed related to sort:
```
Test Suites: 32 failed, 208 passed, 240 total
Tests:       75 failed, 1207 passed, 1282 total
```
```
'Cypher directive > LIMIT happens before custom Cypher if not sorting on the custom Cypher field',
'https://github.com/neo4j/graphql/issues/2267 > sort should be correct when querying interface relationship field',
'tck/rfcs/query-limits > Field Level Query Limits > should extend the limit to the connection field if `first` provided',
'tck/rfcs/query-limits > Field Level Query Limits > should extend the limit to the connection field if `first` provided, honouring the `max` argument',
'tck/rfcs/query-limits > Field Level Query Limits > should limit the connection field level query',
'tck/rfcs/query-limits > Field …
```

Sort limit translation layer

---

packages/graphql/src/translate/queryAST/factory/OperationFactory.ts
packages/graphql/tests/tck/directives/interface-relationships/read.test.ts
packages/graphql/tests/tck/fragments.test.ts
packages/graphql/tests/tck/issues/583.test.ts

```
Test Suites: 30 failed, 210 passed, 240 total
Tests:       70 failed, 1212 passed, 1282 total
```
```
'Cypher Fragment > Fragment On Interface',
'Cypher Fragment > Fragment On Union',
'Interface Relationships > Simple Interface Relationship Query',
'Interface Relationships > Simple Interface Relationship Query For Non-Array Field',
'https://github.com/neo4j/graphql/issues/583 > Should resolve properties from common interface'
]
```

Collect interfaces for concrete entities when translating read

---

packages/graphql/src/schema-model/attribute/Attribute.ts
packages/graphql/src/schema-model/entity/ConcreteEntity.ts
packages/graphql/src/schema-model/parser/parse-attribute.ts

There were still some missing cases where in the schema we defaulted the description to an empty string instead of letting it be undefined.
Low

Do not default description to empty string

---

packages/graphql/src/translate/queryAST/ast/QueryASTNode.ts
packages/graphql/src/translate/queryAST/ast/filters/RelationshipFilter.ts
packages/graphql/src/translate/queryAST/ast/filters/authorization-filters/AuthRelationshipFilter.ts
packages/graphql/src/translate/queryAST/ast/filters/authorization-filters/AuthorizationFilters.ts
packages/graphql/src/translate/queryAST/ast/filters/authorization-filters/AuthorizationRuleFilter.ts
packages/graphql/src/translate/queryAST/ast/operations/ConnectionReadOperation.ts
packages/graphql/src/translate/queryAST/ast/operations/ReadOperation.ts
packages/graphql/src/translate/queryAST/ast/operations/interfaces/InterfaceConnectionPartial.ts
packages/graphql/src/translate/queryAST/ast/operations/interfaces/InterfaceReadPartial.ts
packages/graphql/tests/tck/directives/authorization/arguments/allow/allow.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/allow/interface-relationships/implementation-allow.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/roles-where.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/where/interface-relationships/implementation-where.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/where/where.test.ts
packages/graphql/tests/tck/directives/authorization/projection-connection-union.test.ts
packages/graphql/tests/tck/directives/authorization/projection-connection.test.ts
packages/graphql/tests/tck/directives/node/node-with-auth-projection.test.ts

Fix relationship filters on 1-1 relationships.
Note that some tck tests have been changed, going from `varx` to `xcount` in some variables. These were already updated before and now are reverted back to how they are in dev branch to reduce diff in the translation refactor
```
Test Suites: 20 failed, 220 passed, 240 total
Tests:       45 failed, 1237 passed, 1282 total
```
```
'@auth allow on specific interface implementation > Read Two Relationships',
'@auth allow on specific interface implementation > read allow protected interface relationship',
'Cypher Auth Allow > Read Two Relationships',
'Cypher Auth Where > Read Node',
'Cypher Auth Where > Read Node + User Defined Where',
'Cypher Auth Where > Read Union',
'Cypher Auth Where > Read Union Relationship + …
```

Relationship filters on 1-1 relationships

---

packages/graphql/src/schema-model/entity/model-adapters/ConcreteEntityAdapter.ts
packages/graphql/src/schema-model/entity/model-adapters/InterfaceEntityAdapter.ts
packages/graphql/src/schema/resolvers/query/global-node.ts
packages/graphql/src/translate/queryAST/factory/FieldFactory.ts
packages/graphql/src/translate/queryAST/factory/FilterFactory.ts
packages/graphql/src/translate/translate-read.ts

```
'Global nodes > it should fetch the correct node and fields',
'Global nodes > it should project the correct node and fields when id is the idField',
'Global nodes > it should project the correct selectionSet when id is used as a where argument',
'Global nodes > it should project the param as an integer when the underlying field is a number (fixes 1560)'
]
Regressions in branch B:  []
```

Fix global nodes

---

packages/graphql/src/schema-model/annotation/CustomResolverAnnotation.ts
packages/graphql/src/schema-model/generate-model.ts
packages/graphql/src/schema-model/parser/annotations-parser/custom-resolver-annotation.test.ts
packages/graphql/src/schema-model/parser/annotations-parser/custom-resolver-annotation.ts
packages/graphql/src/schema-model/parser/definition-collection.ts
packages/graphql/src/schema-model/parser/parse-attribute.ts
packages/graphql/src/schema/get-custom-resolver-meta.ts
packages/graphql/src/translate/queryAST/factory/FieldFactory.ts
packages/graphql/tests/tck/directives/customResolver.test.ts

```
'@customResolver directive > Require fields on nested interfaces > should not over fetch when no required fields are manually selected',
'@customResolver directive > Require fields on nested interfaces > should not over fetch when some required fields are manually selected',
'@customResolver directive > Require fields on nested types > should not over fetch when no required fields are manually selected',
'@customResolver directive > Require fields on nested types > should not over fetch when some required fields are manually selected',
'@customResolver directive > Require fields on nested unions > should not over fetch when no required fields are manually selected',
'@customResolver directive > Require fields on nested unions > should not over fetch when …
```

Custom resolvers

---

packages/graphql/src/schema-model/relationship/model-adapters/RelationshipAdapter.ts

Reuse the already implemented `connectionFieldTypename` and `relationshipFieldTypename`.

Use schema generator type names for relationship

---

packages/graphql-toolbox/package.json

At some point during the 4.0.0 release, Toolbox versions got a bit messy, meaning that the current proposal by changesets has actually already been released. This bumps the version so that changesets releases the next version along.

Bump Toolbox version to match current max

---

.github/workflows/changesets.yml

The release failed to merge `dev` into `master` due to missing git config. This PR addresses that.

Add missing git config to changesets workflow

---

packages/graphql/src/schema-model/relationship/model-adapters/RelationshipAdapter.ts
packages/graphql/tests/schema/lowercase-type-names.test.ts

In the schema generation refactor there was an issue where we uppercased getAggregationFieldTypename's target name which highlighted that we weren't explicitly supporting lowercase type names. This PR fixes the underlying schema model problem while also adding a test for future regressions.
Low

Ensure we can have lowercase type names

---

packages/graphql/src/translate/queryAST/factory/FieldFactory.ts
packages/graphql/src/translate/queryAST/factory/FilterFactory.ts
packages/graphql/tests/integration/subscriptions/spatial-types.int.test.ts

Fix Carterian Point queries
```
'CartesianPoint > enables query of a node with a cartesian point',
'CartesianPoint > enables query of a node with a cartesian-3d point',
'Subscriptions to spatial types > query type with CartesianPoint field and filters',
'[CartesianPoint] > enables query of a node with multiple cartesian points',
'[CartesianPoint] > enables query of a node with multiple cartesian-3d points'
```

Fix spatial types

---

packages/graphql/src/translate/queryAST/ast/operations/composite/CompositeConnectionPartial.ts
packages/graphql/src/translate/queryAST/ast/operations/composite/CompositeConnectionReadOperation.ts
packages/graphql/src/translate/queryAST/ast/operations/composite/CompositeReadOperation.ts
packages/graphql/src/translate/queryAST/ast/operations/composite/CompositeReadPartial.ts
packages/graphql/src/translate/queryAST/factory/OperationFactory.ts

As title, rename  `Interface{Read/ConnectionRead}`  to `Composite{Read/ConnectionRead}`, in fact the operations under the name `Interface{Read/ConnectionRead}` are used to implement both union and interface types.

Rename Interface operations to Composite operations.

---

.changeset/sixty-pets-wave.md
packages/graphql/src/graphql/directives/arguments/scalars/ScalarOrEnum.ts

Toolbox shows a linting error for valid `@default` argument when using an enum. This PR adds a `Kind.ENUM` case to `parseLiteral` in `ScalarOrEnum`
Low
Closes  #4023

Fix Toolbox linting error on Enum default directive arguments

---

.changeset/warm-trainers-repeat.md
packages/ogm/src/classes/OGM.test.ts
packages/ogm/src/classes/OGM.ts

This PR makes it so that the `OGM.init()` call will throw errors instead of silently capturing them.
Low
Closes  #4123

OGM: throw errors caught in createInitializer

---

packages/graphql/tests/performance/graphql/connections.graphql
packages/graphql/tests/performance/graphql/sorting-and-cypher.graphql
packages/graphql/tests/performance/graphql/sorting.graphql
packages/graphql/tests/performance/typedefs.ts

Moved sort tests to sort files. Added test coverage for cases when multiple cypher fields with pagination and sorting are applied. Added a more expensive `@cypher` field called `otherMoviesWhereActorsActedIn` which returns all the other movies where the actors have also acted.

improve performance test coverage around sorting and cypher

---

.github/workflows/performance-tests.yml

We should only need to run performance tests when tck tests have changed, so this PR narrows down the path
Low

Only run performance tests when tck tests have had changes

---

packages/introspector/tests/integration/graphql/label-injection.test.ts

Two tests are using the same database name and this cause problem with the latest neo4j images.

Fix pipeline (DBNAME collision)

---

.changeset/flat-badgers-itch.md
packages/graphql/src/schema/validation/custom-rules/valid-types/valid-directive-combination.ts
packages/graphql/src/schema/validation/validate-document.test.ts

This PR fixes the validation for directive combination, more specifically the directive combination logic for inherited fields. It was before collecting all the directives on the inherited field, from all the implementing types. It is now returning multiple directive combinations between the Interface field and A Concrete Type field, as many combinations as many implementing types there are.
Closes #4232 

Fix incorrect directive combination for inherited fields

---

.changeset/forty-shrimps-cover.md
package.json
packages/graphql/src/translate/authorization/compatibility/create-authorization-after-and-params.ts
packages/graphql/src/translate/authorization/compatibility/create-authorization-before-and-params.ts
packages/graphql/src/translate/create-connect-and-params.ts
packages/graphql/src/translate/create-create-and-params.ts
packages/graphql/tests/integration/issues/4214.int.test.ts
packages/graphql/tests/tck/array-methods.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/allow/allow.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/allow/interface-relationships/implementation-allow.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/bind/bind.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/bind/interface-relationships/implementation-bind.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/roles-where.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/roles/roles.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/where/interface-relationships/implementation-where.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/where/where.test.ts
packages/graphql/tests/tck/issues/2789.test.ts
packages/graphql/tests/tck/issues/3901.test.ts
packages/graphql/tests/tck/issues/3929.test.ts
packages/graphql/tests/tck/issues/4118.test.ts
packages/graphql/tests/tck/issues/4170.test.ts
packages/graphql/tests/tck/issues/4214.test.ts
packages/graphql/tests/tck/operations/batch/batch-create-auth.test.ts
yarn.lock

This PR modifies the prefix with which authorization subqueries are being built for creates by appending "before" or "after" depending on which function is being built. It also takes into account the create index for further collision protection. Once again, we should move creates to the new Translation Layer to fix these sort of problems once and for all.
Closes #4214 

Fix authorization before and after parameter name clash

---

packages/graphql/src/schema/resolvers/query/global-node.ts
packages/graphql/src/translate/translate-read.ts

This PR migrate the global node resolver to use new translation-layer

Migrate global node resolver to use new translation-layer

---

renovate.json

Please see https://docs.renovatebot.com/presets-config/#configbest-practices and go down the docs tree for details.
But does things such as:
* Pin GitHub Actions to digests
* Pin Docker to digests
* Replace known package names (such as `apollo-server` is now `@apollo/server`)
* Group together certain known dependencies and monorepos

Apply Renovate best practices by default

---

packages/graphql-toolbox/package.json
packages/graphql-toolbox/playwright.config.ts
packages/graphql-toolbox/src/modules/AppSettings/AppSettings.tsx
yarn.lock

In this PR:
- We update the year to 2024 in the Toolbox settings
- Downgrade codemirror packages to conform to the fixed-version peer dependencies in `cm6-graphql`
- Add a CI only `maxFailures` to playwright config
- Use `defineConfig` is playwright config

Fix toolbox failing tests

---

.changeset/two-phones-look.md
packages/graphql/src/translate/create-create-and-params.ts
packages/graphql/tests/integration/issues/4429.int.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/bind/interface-relationships/implementation-bind.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/roles-where.test.ts
packages/graphql/tests/tck/directives/authorization/arguments/where/where.test.ts
packages/graphql/tests/tck/issues/3901.test.ts
packages/graphql/tests/tck/issues/4118.test.ts
packages/graphql/tests/tck/issues/4170.test.ts
packages/graphql/tests/tck/issues/4214.test.ts
packages/graphql/tests/tck/issues/4223.test.ts
packages/graphql/tests/tck/issues/4429.test.ts
packages/graphql/tests/tck/operations/batch/batch-create-auth.test.ts

A much tidier fix for this was in place, but it fell apart the second you got too deep into the input because prefixes begun to get overwritten. This replaces it with a less tidy solution of appending at every level, but it won't suffer from collisions.
Closes #4429

Fix authorization variable naming for create operations

---

package.json
packages/graphql-toolbox/package.json
yarn.lock

Previously due to an error in the workflow it meant renovate PRs were being merged even when quality-gate was not passing. This has been addressed in a separate PR. This PR is to revert to a state where renovate will subsequently create a new PR which should then fail to automerge.
Low

Revert codemirror resolutions

---

.changeset/sharp-tigers-serve.md
packages/graphql/src/schema-model/attribute/model-adapters/AttributeAdapter.ts
packages/graphql/src/schema-model/entity/model-adapters/ConcreteEntityAdapter.ts
packages/graphql/src/schema-model/entity/model-adapters/InterfaceEntityAdapter.ts
packages/graphql/src/schema-model/relationship/model-adapters/RelationshipAdapter.ts
packages/graphql/src/schema/generation/implementation-inputs.ts
packages/graphql/src/schema/generation/where-input.ts
packages/graphql/src/schema/get-where-fields.ts
packages/graphql/src/schema/make-augmented-schema.ts
packages/graphql/src/schema/subscriptions/generate-subscription-types.ts
packages/graphql/src/schema/subscriptions/generate-subscription-where-type.ts
packages/graphql/src/schema/to-compose.ts
packages/graphql/tests/schema/directives/filterable.test.ts
packages/graphql/tests/schema/directives/selectable.test.ts
packages/graphql/tests/schema/directives/settable.test.ts
packages/graphql/tests/schema/experimental-schema/directives/filterable.test.ts
packages/graphql/tests/schema/experimental-schema/directives/selectable.test.ts
packages/graphql/tests/schema/experimental-schema/directives/settable.test.ts
packages/graphql/tests/schema/experimental-schema/issues/3439.test.ts
packages/graphql/tests/schema/experimental-schema/subscriptions.test.ts
packages/graphql/tests/schema/issues/3439.test.ts
packages/graphql/tests/schema/issues/3537.test.ts
packages/graphql/tests/schema/subscriptions.test.ts

Harmonize the generation of SubscriptionWhere- & Where- input-types, so they reuse the same logic
This fixes 2 issues:
1. The correct usage of non-nullable array elements
2. the correct handling of interfaces with enabled experimental flag (`typename_IN`)

Harmonize the generation of SubscriptionWhere- & Where- input-types, so they reuse the same logic
