- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/----bug-report.md
- .github/ISSUE_TEMPLATE/----questions-help.md
- .github/ISSUE_TEMPLATE/--regression-report.md
- .vscode/extensions.json
- README.md
- docs/markdown/CONTRIBUTING.md
- docs/markdown/DEVELOPING.md
- Added developer guide
- Tweaked contributor guide
- Added `CODEOWNERS` file
> Md changes

- docs/antora/antora.yml
> Update version and mark prerelease

- docs/asciidoc/guides/migration-guide/type-definitions.adoc
- docs/asciidoc/type-definitions/types.adoc
- packages/graphql/src/schema/make-augmented-schema.ts
- packages/graphql/src/schema/scalars/Date.ts
- packages/graphql/src/schema/validation/scalars.ts
- packages/graphql/tests/integration/types/date.int.test.ts
- packages/graphql/tests/tck/tck-test-files/cypher/types/date.md
- packages/graphql/tests/tck/tck-test-files/schema/types/date.md
- packages/graphql/tests/tck/tck.test.ts
This introduces a `Date` to complement the temporal type `DateTime` we already have.
Fixes #244 
> Add `Date` scalar type mapped to Neo4j Date type

- docs/asciidoc/guides/migration-guide/type-definitions.adoc
- docs/asciidoc/type-definitions/types.adoc
- packages/graphql/src/schema/make-augmented-schema.ts
- packages/graphql/src/schema/scalars/Date.ts
- packages/graphql/src/schema/validation/scalars.ts
- packages/graphql/tests/integration/types/date.int.test.ts
- packages/graphql/tests/integration/types/point.int.test.ts
- packages/graphql/tests/tck/tck-test-files/cypher/types/date.md
- packages/graphql/tests/tck/tck-test-files/schema/types/date.md
- packages/graphql/tests/tck/tck.test.ts
> Bring 2.0.0 inline with master

- packages/graphql/src/translate/connection/create-connection-and-params.ts
- packages/graphql/tests/integration/auth/allow.int.test.ts
- packages/graphql/tests/integration/auth/where.int.test.ts
- packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/arguments/where.md
- packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/projection-connection-union.md
- packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/projection-connection.md
Adds auth on the connections. This only includes auth on nodes.
> Feat/Connection Auth

- docs/asciidoc/type-definitions/relationships.adoc
- packages/graphql/src/schema/make-augmented-schema.ts
- packages/graphql/src/translate/create-connect-and-params.ts
- packages/graphql/src/translate/create-create-and-params.ts
- packages/graphql/src/translate/create-update-and-params.ts
- packages/graphql/src/translate/translate-update.ts
- packages/graphql/tests/integration/connection-resolvers-int.test.ts
- packages/graphql/tests/integration/connections/enums.int.test.ts
- packages/graphql/tests/integration/relationship-properties/connect.int.test.ts
- packages/graphql/tests/integration/relationship-properties/create.int.test.ts
- packages/graphql/tests/tck/tck-test-files/cypher/connections/relationship_properties/connect.md
- packages/graphql/tests/tck/tck-test-files/cypher/connections/relationship_properties/create.md
- packages/graphql/tests/tck/tck-test-files/cypher/connections/relationship_properties/update.md
- packages/graphql/tests/tck/tck-test-files/schema/connections/enums.md
- packages/graphql/tests/tck/tck-test-files/schema/connections/unions.md
- packages/graphql/tests/tck/tck-test-files/schema/relationship-properties.md
Hopefully less commits in this PR!
#192 
> Replace instances of "properties" with "relationship"

- .github/CODEOWNERS
- README.md
Adds some links to content about the lib on the main readme.
> Docs media

- packages/graphql/src/translate/create-projection-and-params.ts
- packages/graphql/tests/integration/custom-resolvers.int.test.ts
Fix primitive arrays being returned from custom Cypher fields
> Fix primitive arrays being returned from custom Cypher fields

- packages/graphql/src/translate/create-update-and-params.ts
- packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/arguments/bind.md
- packages/graphql/tests/tck/tck-test-files/cypher/issues/324.md
- packages/graphql/tests/tck/tck-test-files/cypher/operations/update.md
Resolves the error in the linked issue.
#324 
> Add missing parameters to apoc.do.when which might be needed within

- README.md
Adds a pointer for 2.0.0 on the home page.
> docs: add 2.0.0 banner on home page

- docs/asciidoc/ogm/index.adoc
- docs/asciidoc/ogm/private.adoc
- docs/asciidoc/queries.adoc
> Further documentation tweaks

- docs/asciidoc/filtering.adoc
- docs/asciidoc/guides/migration-guide/type-definitions.adoc
- docs/asciidoc/type-definitions/types.adoc
Documentation tweaks:
- Remove references to specific temporal and spatial types on "Filtering" page, instead link to top-level header for each
> Tweaks to documentation 2021/08/02

- packages/graphql/src/schema/resolvers/count.test.ts
- packages/graphql/src/schema/resolvers/count.ts
I fixed the issue #425 but I don't know if there is another reason for that issue to happen.
Please investigate that in the review.
https://github.com/neo4j/graphql/issues/425
> Fixed issue #425 (broken count)

- .github/workflows/release.yml
Adds Slack notifications to release workflow - message body configured in the Slack workflow itself.
> Add Slack notifications to release workflow

- packages/graphql/src/translate/create-set-relationship-properties-and-params.ts
- packages/graphql/src/translate/create-set-relationship-properties.ts
- packages/graphql/src/translate/create-update-and-params.ts
- packages/graphql/tests/integration/autogenerate.int.test.ts
- packages/graphql/tests/integration/timestamps.int.test.ts
Fixed with the solution as proposed by @maxwellprioritynetworks, thanks!
#456 
> Fix @id and @timestamp for relationship properties

- packages/graphql/src/translate/create-disconnect-and-params.test.ts
- packages/graphql/src/translate/create-disconnect-and-params.ts
- packages/graphql/tests/integration/issues/440.int.test.ts
- packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/arguments/allow.md
- packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/arguments/bind.md
- packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/arguments/is-authenticated.md
- packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/arguments/roles.md
- packages/graphql/tests/tck/tck-test-files/cypher/directives/auth/arguments/where.md
- packages/graphql/tests/tck/tck-test-files/cypher/nested-unions.md
- packages/graphql/tests/tck/tck-test-files/cypher/operations/update.md
- packages/graphql/tests/tck/tck-test-files/cypher/pringles.md
- packages/graphql/tests/tck/tck-test-files/cypher/union.md
Idem to https://github.com/neo4j/graphql/pull/341 but for `disconnect` operations.
https://github.com/neo4j/graphql/issues/440
> Wrap disconnect operations in subqueries

- docs/modules/ROOT/pages/ogm/examples/custom-resolvers.adoc
Fix two simple errors in example code of Custom Resolvers documentation.
No issue was created.
> fix small errors in example code

- examples/neo-push/server/package.json
- yarn.lock
Just bumps a neo-push dependency version - tests were not passing.
> Bump neo4j-driver dependency in neo-push so that tests pass

- examples/neo-push/server/package.json
- package.json
- yarn.lock
Ensuring 4.4.0 driver compatibility.
> Bump neo4j-driver

- .github/workflows/bug-confirmed-comment.yml
- .github/workflows/bug-confirmed-label.yml
- .github/workflows/bug-report.yml
- .github/workflows/lint-github-actions.yml
Adds automations for Bug Triage project.
> Add automations for bug triage project

- examples/neo-push/server/package.json
- yarn.lock
> Fix yarn install for PRs

- .github/workflows/hotfix.yml
- config/release-changelog-builder-action/configuration-graphql-hotfix.json
- config/release-changelog-builder-action/configuration-ogm-hotfix.json
- config/release-changelog-builder-action/configuration-ogm.json
A clunky way of generating a different changelog for hotfixes and releases.
Our workflows are ripe for breaking out into reuseable workflows, but this does not need to happen now.
> Ensure changelog is correct for releases and hotfixes

- packages/graphql/src/schema/create-relationship-fields/index.ts
- packages/graphql/tests/schema/interface-relationships.test.ts
Adds some missing conditional logic which was causing input fields to be added where they shouldn't.
Closes #868
> Remove spurious create input fields for interface relationships

- packages/graphql/tests/integration/issues/894.int.test.ts
Due to compatibility issues, #894 integration tests do not use unique types. This PR changes this to makes these tests more reliable
> Update 894 integration tests

- docs/modules/ROOT/pages/introduction.adoc
This docs change would help me install the required plugin to be able to use DateTimes.
[Please provide a link to the GitHub issue in which the proposal for this work was discussed below. ](https://github.com/neo4j/graphql/issues/941)
It's important that changes are discussed in advance to make sure we choose the right solution and to avoid duplication of effort.
Closes:
- 
> Explain how to install plugins for people unfamiliar with Neo4j

- package.json
- packages/graphql/package.json
- packages/graphql/tests/integration/neo4j.ts
- packages/introspector/package.json
- packages/ogm/package.json
- packages/ogm/tests/integration/neo4j.ts
- packages/package-tests/typescript/package.json
- yarn.lock
Updates typescript and fix issues
> Typescript update

- packages/package-tests/apollo/package.json
- packages/package-tests/apollo/server.test.js
Update dependencies with breaking changes
* `node-fetch` --> `cross-fetch`
> Change node-fetch to cross-fetch

- docs/modules/ROOT/pages/guides/v3-migration/index.adoc
Missing changes for migration guide
> update relationship cardinality section on migration guide

- docs/rfcs/rfc-000-template.md
Upon request from the Neo4j Security team a "security prompt" is added that we are to discuss appropriately for each RFC.
> Security prompt in RFC template

- packages/graphql/tests/integration/directives/cypher.int.test.ts
Causing the vast majority of test failures on `dev`.
> Fix flaky tests for Cypher default values

- packages/graphql/src/translate/connect-or-create/create-connect-or-create-and-params.ts
- packages/graphql/src/translate/create-create-and-params.ts
- packages/graphql/src/translate/create-update-and-params.ts
- packages/graphql/src/translate/translate-update.ts
- packages/graphql/src/translate/utils/wrap-in-call.ts
- packages/graphql/tests/integration/issues/1127.int.test.ts
Adds an appropriate `WITH` clause before performing `connectOrCreate`.
Closes #1127.
> Fix extra node being created by connectOrCreate

- docs/modules/ROOT/pages/guides/migration-guide/server.adoc
- packages/graphql/README.md
- packages/ogm/README.md
> Readme Fixes

- packages/graphql/src/translate/create-aggregate-where-and-params.ts
- packages/graphql/tests/integration/directives/auth/allow-unauthenticated.int.test.ts
- packages/graphql/tests/integration/directives/auth/jwks-endpoint.int.test.ts
- packages/graphql/tests/integration/directives/timestamp/time.int.test.ts
- packages/graphql/tests/tck/tck-test-files/advanced-filtering.test.ts
- packages/graphql/tests/tck/tck-test-files/alias.test.ts
- packages/graphql/tests/tck/tck-test-files/arrays.test.ts
- packages/graphql/tests/tck/tck-test-files/fragments.test.ts
- packages/graphql/tests/tck/tck-test-files/null.test.ts
- packages/graphql/tests/tck/tck-test-files/pagination.test.ts
- packages/graphql/tests/tck/tck-test-files/types/bigint.test.ts
- packages/graphql/tests/utils/builders/driver-builder.ts
- packages/graphql/tests/utils/create-jwt-request.ts
- packages/package-tests/apollo/server.test.js
Some low hanging fruits on eslint errors
> Fix some simple eslint errors

- docs/modules/ROOT/pages/type-definitions/autogeneration.adoc
Fixing the docs for the `callback` directive.
> Fix: Autogenerate properties - callback, docs

- docs/modules/ROOT/pages/auth/setup.adoc
Update to document supported algorithms
Adds documentation of supported algorithms to base decode function.
> update to include supported algorithms

- packages/graphql/src/schema/resolvers/field/numerical.ts
Update numerical.ts to work for all Integerable values
> Update numerical.ts to work for all Integerable values

- renovate.json
> Configure Renovate to group together `@neo4j/ndl` dependencies

- docs/modules/ROOT/pages/subscriptions/plugins/amqp.adoc
- packages/plugins/graphql-plugin-subscriptions-amqp/README.md
- packages/plugins/graphql-plugin-subscriptions-amqp/src/index.test.ts
- packages/plugins/graphql-plugin-subscriptions-amqp/src/index.ts
- packages/plugins/graphql-plugin-subscriptions-amqp/tests/e2e/apollo-subscriptions.e2e.test.ts
- packages/plugins/graphql-plugin-subscriptions-amqp/tests/e2e/rabbitmq.e2e.test.ts
- packages/plugins/graphql-plugin-subscriptions-amqp/tests/e2e/setup/plugin.ts
Please provide a description of the work completed in this branch.
Please provide a link to the GitHub issue in which the proposal for this work was discussed below. 
It's important that changes are discussed in advance to make sure we choose the right solution and to avoid duplication of effort.
Closes:
- 
> Rename subscriptions plugin

- .github/workflows/release.yml
> Allow release to continue if Aura tests fail

- packages/graphql/tests/integration/aggregations/top-level/alias.int.test.ts
- packages/graphql/tests/integration/aggregations/top-level/many.int.test.ts
- packages/graphql/tests/integration/aggregations/top-level/string.int.test.ts
- packages/graphql/tests/integration/connections/nested.int.test.ts
- packages/graphql/tests/integration/interface-relationships/read.int.test.ts
- packages/graphql/tests/integration/issues/582.int.test.ts
- packages/graphql/tests/integration/issues/630.int.test.ts
Some integration tests still use static types and where causing some false negatives when running on non empty databases
> Fix some unrealiable integration tests

- package.json
- tsconfig.base.json
- yarn.lock
As per title with deprecation of Node.js 12.
> Upgrade TS config base to `@tsconfig-node14`

- docs/rfcs/rfc-006-auth-plugin.md
Please provide a description of the work completed in this branch.
Please provide a link to the GitHub issue in which the proposal for this work was discussed below. 
It's important that changes are discussed in advance to make sure we choose the right solution and to avoid duplication of effort.
Closes:
- 
> Added missing '.' before well-known in url for JWKS

- packages/graphql-toolbox/src/modules/TopBar/TopBar.tsx
> Revert "Feat: Toolbox - remove the beta tag"

- .github/workflows/changesets-dev.yml
- .github/workflows/changesets-master.yml
These workflows will keep open two PRs containing the WIP changelog from both `master` and `dev`. Next step is to automate the release workflow when these are merged.
> Add workflows for changesets

- packages/graphql/tests/performance/performance.json
This PR updates performance stats generated by `yarn performance -u`
> Update performance stats

- packages/graphql/tests/performance/cypher/basic-cypher.cypher
- packages/graphql/tests/performance/performance.json
> Add some cypher tests and update stats

- .github/workflows/sonarcloud.yml
Adding SonarCloud scan for graphql-plugin-subscriptions-amqp.
> Feat: Adding SonarCloud scan for graphql-plugin-subscriptions-amqp

- .changeset/eight-seals-stare.md
- packages/graphql/CHANGELOG.md
- packages/graphql/package.json
- packages/ogm/CHANGELOG.md
- packages/ogm/package.json
> Manual changelog

- .changeset/config.json
- .github/workflows/reusable-aura-tests.yml
- package.json
- yarn.lock
Provides some fixes and improvements to the new release pipeline.
> Release workflow fixes

- .changeset/eight-seals-stare.md
- packages/graphql/CHANGELOG.md
- packages/graphql/package.json
- packages/ogm/CHANGELOG.md
- packages/ogm/package.json
> Revert "Manual changelog"

- .changeset/eight-seals-stare.md
- packages/graphql/CHANGELOG.md
- packages/graphql/package.json
- packages/ogm/CHANGELOG.md
- packages/ogm/package.json
> Revert "Revert "Manual changelog""

- docs/modules/ROOT/pages/subscriptions/events/delete.adoc
I may be misunderstanding this section- it's pretty late and I'm out of coffee.
My proposal is based off this line: "This lets you filter on top-level properties of the deleted nodes.
Only events matching these properties and type will be returned to this subscription."
> Revise graphql statement

- docs/rfcs/rfc-021-database-info.md
Contains details of the RFC Database info
> RFC Database info

- packages/graphql/tests/integration/issues/1364.int.test.ts
- packages/graphql/tests/integration/issues/560.int.test.ts
- packages/graphql/tests/integration/issues/988.int.test.ts
- packages/graphql/tests/integration/sort.int.test.ts
This PR adds bookmarks in some integration tests to fix some flaky tests
> Add session bookmarks to some integration tests

- .changeset/chatty-lions-jump.md
- packages/graphql/src/translate/create-projection-and-params.ts
- packages/graphql/tests/integration/issues/1848.int.test.ts
- packages/graphql/tests/tck/tck-test-files/issues/1848.test.ts
Issue: #1848
Adds white space between `AND` and `this_hasFeedItems`.
Closes:
- #1848
> Fix: Cypher generation syntax error

- packages/graphql/tests/integration/issues/1050.int.test.ts
Fixes another flaky test from last night's test run.
> Pass bookmarks through test

- docs/modules/ROOT/pages/index.adoc
As seen on https://neo4j.com/docs/graphql-manual/current/
> Fixing the word authorization from British to American spelling

- packages/graphql/tests/performance/graphql/query.graphql
> Add performance test for array filtering

- packages/graphql/src/translate/cypher-builder/CypherBuilder.ts
- packages/graphql/src/translate/cypher-builder/clauses/Match.test.ts
- packages/graphql/src/translate/cypher-builder/clauses/Match.ts
- packages/graphql/src/translate/cypher-builder/sub-clauses/Delete.ts
- packages/graphql/src/translate/cypher-builder/sub-clauses/Remove.ts
- packages/graphql/tests/integration/unions.int.test.ts
This PR adds support for the following statements in CypherBuilder:
* `OPTIONAL MATCH`
* `DELETE`
* `DETACH DELETE`
* `REMOVE`
> cypher builder: Delete and remove

- packages/graphql/tests/performance/graphql/sorting.graphql
- packages/graphql/tests/performance/utils/ResultsDisplay.ts
This PR adds some performance tests on sorting and improves the display by changing the colour of tests not found in compared results
> Sort performance tests

- packages/graphql/src/translate/cypher-builder/sub-clauses/OrderBy.test.ts
- packages/graphql/src/translate/cypher-builder/sub-clauses/OrderBy.ts
- packages/graphql/tests/integration/sort.int.test.ts
> Add tests on using skip with limit

- packages/graphql/src/translate/create-auth-and-params.ts
- packages/graphql/tests/integration/unions.int.test.ts
- packages/graphql/tests/tck/tck-test-files/union.test.ts
This PR fixes the tests regading allow auth
> 1953 auth allow rule incorrectly compared in unions

- packages/graphql/tests/tck/interfaces.test.ts
- packages/graphql/tests/tck/issues/2022.test.ts
This PR just moves a couple of tck files out of `tck-test-files` folder
> Move tck files

- packages/graphql/src/translate/cypher-builder/CypherBuilder.ts
- packages/graphql/src/translate/cypher-builder/clauses/sub-clauses/Set.ts
- packages/graphql/src/translate/cypher-builder/expressions/map/MapExpr.ts
- packages/graphql/src/translate/cypher-builder/expressions/map/MapProjection.test.ts
- packages/graphql/src/translate/cypher-builder/expressions/map/MapProjection.ts
- packages/graphql/src/translate/cypher-builder/types.ts
- packages/graphql/src/translate/cypher-builder/utils/serialize-map.ts
This allows for map projections such as `this0 { .name }`
> Add MapProjection to CypherBuilder

- packages/graphql/tests/integration/issues/1287.int.test.ts
Issue #1287 was fixed in `3.6.0` however, it was missing an integration test to avoid regression
> Add integration test for #1287

- .github/workflows/lint-github-actions.yml
- .github/workflows/pull-requests.yml
Specify the node_options as input to reviewdog instead of as env
> Set node_options in reviewdog inputs

- docs/modules/ROOT/pages/array-methods.adoc
Change wording from push to pop for pop example
> docs: change wording from push to pop for pop example

- docs/rfcs/rfc-024-unwind-create.md
Fix complex example with relationship properties
> Update complex example

- packages/graphql/tests/integration/issues/1121.int.test.ts
- packages/graphql/tests/integration/issues/2022.int.test.ts
- packages/graphql/tests/integration/issues/interface-post-multi-create.ts
Adds a test for #1121 to prevent further regressions.
Closes #1121
> Add test for 1121, remove some unnecessary debug logging

- packages/graphql/tests/integration/issues/1049.int.test.ts
Adds a test for #1049 to prevent future regressions.
Closes #1049
> Add test for 1049

- packages/graphql/src/translate/cypher-builder/Pattern.ts
- packages/graphql/src/translate/cypher-builder/variables/NodeRef.ts
- packages/graphql/src/translate/cypher-builder/variables/RelationshipRef.test.ts
- packages/graphql/src/translate/cypher-builder/variables/RelationshipRef.ts
This PR adds the `relatedTo` method to NodeRef and minor improvements on how cypher is generated
> Adds relatesTo and minor improvements to relationships in cypherbuilder

- packages/graphql/src/translate/create-connect-or-create-and-params.ts
- packages/graphql/src/translate/create-projection-and-params.ts
- packages/graphql/src/translate/cypher-builder/clauses/Call.test.ts
- packages/graphql/src/translate/cypher-builder/clauses/Call.ts
- packages/graphql/src/translate/cypher-builder/clauses/Create.ts
- packages/graphql/src/translate/cypher-builder/clauses/Match.ts
- packages/graphql/src/translate/cypher-builder/clauses/Merge.ts
- packages/graphql/src/translate/cypher-builder/clauses/Return.ts
- packages/graphql/src/translate/cypher-builder/clauses/Unwind.ts
- packages/graphql/src/translate/cypher-builder/clauses/With.ts
- packages/graphql/src/translate/cypher-builder/clauses/utils/mixin.ts
- packages/graphql/src/translate/cypher-builder/examples/call.test.ts
- packages/graphql/src/translate/cypher-builder/expressions/list/ListComprehension.ts
- packages/graphql/src/translate/cypher-builder/expressions/list/PatternComprehension.ts
- packages/graphql/src/translate/cypher-builder/expressions/procedures/db.ts
- tsconfig.base.json
Minor improvements to cypher builder
* change `.with` to `.innerWith` in `Call`
* Use a decorator for mixins
> Cypher builder improvements

- packages/graphql/tests/integration/issues/1640.int.test.ts
This PR adds integration tests to the, now fixed, bug #1640
> Add integration test for 1640

- packages/graphql/tests/performance/graphql/delete.graphql
- packages/graphql/tests/performance/performance.ts
- packages/graphql/tests/performance/types.ts
- packages/graphql/tests/performance/utils/TestRunner.ts
- packages/graphql/tests/performance/utils/collect-test-files.ts
Fix mutation performance tests setup by adding afterEach hooks with a resetDB.
Additional tests for delete added
> Add before and after each hooks to performance tests

- packages/graphql/tests/integration/directives/auth/allow-unauthenticated.int.test.ts
This PR generates unique types for the `allow-unauthenticated` integration test to avoid DB collisions while testing
> Fix flakiness on allow-unauthenticated integration test

- .changeset/bright-seas-listen.md
- packages/graphql/src/translate/connection-clause/create-connection-clause.ts
- packages/graphql/src/translate/cypher-builder/clauses/Call.ts
- packages/graphql/tests/integration/issues/2262.int.test.ts
- packages/graphql/tests/tck/connections/relationship-properties.test.ts
- packages/graphql/tests/tck/issues/1528.test.ts
- packages/graphql/tests/tck/issues/2262.test.ts
- packages/graphql/tests/tck/rfcs/query-limits.test.ts
This PR fixes the regression of having nested and sorted connections with no edges (#2262 )
> 2262 incorrect query results when sorting on a relationship with no edges

- .changeset/tame-avocados-hide.md
- packages/graphql/package.json
- yarn.lock
> Use cypher-builder dependency

- packages/graphql/tsconfig.json
Update tsconfig with ts-node paths
> Update tsconfig with ts-node paths

- packages/graphql/src/translate/batch-create/unwind-create-visitors/UnwindCreateVisitor.ts
- packages/graphql/tests/integration/neo4j.ts
- packages/graphql/tests/tck/connections/relationship_properties/create.test.ts
- packages/graphql/tests/tck/directives/alias.test.ts
- packages/graphql/tests/tck/directives/node/node-additional-labels.test.ts
- packages/graphql/tests/tck/directives/node/node-label.test.ts
- packages/graphql/tests/tck/operations/batch/batch-create-fields.test.ts
- packages/graphql/tests/tck/operations/batch/batch-create.test.ts
- packages/graphql/tests/tck/operations/create.test.ts
- packages/graphql/tests/tck/rfcs/rfc-003.test.ts
Aliases subquery return as required by version 5.
> Fix 5.0 compatibility

- packages/graphql/src/translate/batch-create/unwind-create-visitors/UnwindCreateVisitor.ts
- packages/graphql/tests/integration/neo4j.ts
- packages/graphql/tests/tck/connections/relationship_properties/create.test.ts
- packages/graphql/tests/tck/directives/alias.test.ts
- packages/graphql/tests/tck/directives/node/node-additional-labels.test.ts
- packages/graphql/tests/tck/directives/node/node-label.test.ts
- packages/graphql/tests/tck/operations/batch/batch-create-fields.test.ts
- packages/graphql/tests/tck/operations/batch/batch-create.test.ts
- packages/graphql/tests/tck/operations/create.test.ts
- packages/graphql/tests/tck/rfcs/rfc-003.test.ts
> Revert "Fix 5.0 compatibility"

- .changeset/cyan-carrots-sit.md
- packages/graphql/src/translate/batch-create/unwind-create-visitors/UnwindCreateVisitor.ts
- packages/graphql/tests/tck/connections/relationship_properties/create.test.ts
- packages/graphql/tests/tck/directives/alias.test.ts
- packages/graphql/tests/tck/directives/node/node-additional-labels.test.ts
- packages/graphql/tests/tck/directives/node/node-label.test.ts
- packages/graphql/tests/tck/operations/batch/batch-create-fields.test.ts
- packages/graphql/tests/tck/operations/batch/batch-create.test.ts
- packages/graphql/tests/tck/operations/create.test.ts
- packages/graphql/tests/tck/rfcs/rfc-003.test.ts
Alias subquery returns in UNWIND CREATE
> Alias subquery returns in UNWIND CREATE

- packages/graphql-toolbox/playwright.config.ts
- packages/graphql-toolbox/tests/pages/Login.ts
- packages/graphql-toolbox/tests/urlqueryparameters.test.ts
- packages/graphql/jest.global-setup.js
- packages/graphql/tests/integration/deprecated/fulltext.int.test.ts
- packages/graphql/tests/integration/directives/fulltext.int.test.ts
- packages/graphql/tests/integration/directives/unique.int.test.ts
- packages/graphql/tests/integration/issues/915.int.test.ts
- packages/graphql/tests/integration/multi-database.int.test.ts
- packages/introspector/tests/integration/graphql/graphs.test.ts
- packages/introspector/tests/integration/graphql/nodes.test.ts
We need to wait for the creation of the database.
Also: fix timeouts for flaky e2e tests
> Add WAIT to create database queries

- docs/modules/ROOT/pages/introduction.adoc
Be more specific in terms of supported Neo4j database versions.
> docs: Supported Neo4j versions

- .changeset/perfect-brooms-hunt.md
- packages/cypher-builder/src/Cypher.ts
- packages/cypher-builder/src/expressions/functions/CypherFunctions.test.ts
- packages/cypher-builder/src/expressions/functions/StringFunctions.test.ts
- packages/cypher-builder/src/expressions/functions/StringFunctions.ts
Exposes the `Function` class for arbitrary functions and add the string functions
> Cypher builder string functions

- .changeset/long-mayflies-attack.md
- packages/graphql/package.json
- packages/graphql/src/translate/batch-create/GraphQLInputAST/AST.ts
- yarn.lock
> remove dependency from crypto

- .changeset/twelve-ties-flow.md
- packages/cypher-builder/src/expressions/functions/ListFunctions.test.ts
- packages/cypher-builder/src/expressions/functions/ListFunctions.ts
Adds [`reduce`](https://neo4j.com/docs/cypher-manual/current/functions/list/#functions-reduce) function
> Add reduce Function

- docs/rfcs/rfc-0031-ogm-select.md
> RFC - OGM Select

- .github/pull_request_template.md
Adds a complexity section to pull request template
> Add complexity section to pull request template

- packages/cypher-builder/src/clauses/Union.test.ts
- packages/cypher-builder/src/expressions/Exists.test.ts
- packages/cypher-builder/src/utils/normalize-variable.test.ts
- packages/cypher-builder/src/utils/serialize-map.test.ts
Some unit tests were missing in cypher-builder
> Add missing unit tests on cypher builder

- docs/modules/ROOT/pages/guides/frameworks/nextjs.adoc
> **Note**
> 
Documentation update.
> **Note**
>
> **Note**
>
>  
Supersedes #2303 in absence of a signed CLA.
> Correct GraphQL API URL in Next.js

- .github/workflows/toolbox-deploy.yml
> **Note**
> 
Add env variable to the Toolbox deploy workflow
> **Note**
>
> fix: pass env var in Toolbox deploy workflow

- docs/rfcs/rfc-028-cypher-directive-subquery.md
Updates RFC to cover the new `@cypher` behaviour to be opt-in
> Update cypher rfc with experimental option

- .github/workflows/performance-tests.yml
- packages/graphql/tests/performance/utils/formatters/MarkdownFormatter.ts
Preserves the working directory on checkout
Adds emoji to output for easy reading
Adds schema generation performance timing
> Performance tests updates

- packages/graphql/tests/integration/rfcs/global-authentication-jwks-auth-plugin.int.test.ts
- packages/graphql/tests/performance/performance.ts
- packages/package-tests/babel/index.js
Fix or disable lingering eslint errors
> Fix some lingering eslint errors

- examples/subscriptions/apollo_rabbitmq/README.md
- examples/subscriptions/apollo_rabbitmq/docker-compose.yml
- examples/subscriptions/apollo_rabbitmq/examples.graphql
- examples/subscriptions/apollo_rabbitmq/package-lock.json
- examples/subscriptions/apollo_rabbitmq/package.json
- examples/subscriptions/apollo_rabbitmq/server.js
- examples/subscriptions/apollo_rabbitmq/typedefs.graphql
- examples/subscriptions/yoga_sse/README.md
- examples/subscriptions/yoga_sse/examples.graphql
- examples/subscriptions/yoga_sse/package-lock.json
- examples/subscriptions/yoga_sse/package.json
- examples/subscriptions/yoga_sse/server.js
- examples/subscriptions/yoga_sse/typedefs.graphql
Simple examples on setting up GraphQL subscriptions in Apollo and Yoga
> Apollo and yoga examples on subscriptions

- packages/graphql/tests/performance/performance.ts
- packages/graphql/tests/performance/utils/formatters/MarkdownFormatter.ts
- packages/graphql/tests/performance/utils/formatters/TTYFormatter.ts
Improves markdown output for performance tests
> Improve performance markdown output

- .changeset/clever-experts-return.md
- packages/cypher-builder/src/clauses/Call.test.ts
- packages/cypher-builder/src/clauses/Call.ts
- packages/cypher-builder/src/clauses/mixins/WithUnwind.ts
- packages/graphql/src/translate/projection/subquery/translate-cypher-directive-projection.ts
- packages/graphql/src/translate/translate-top-level-cypher.ts
- packages/graphql/tests/integration/directives/cypher.int.test.ts
- packages/graphql/tests/integration/directives/cypher/column-name.int.test.ts
- packages/graphql/tests/integration/directives/cypher/cypher.int.test.ts
- packages/graphql/tests/tck/directives/cypher.test.ts
As a follow up for #2455 
Adds new behaviour with `columnName` argument to `@cypher` fields.
> Add columnName for field cypher fields

- .github/workflows/reusable-subscriptions-plugin-amqp-e2e-test.yml
Changes e2e plugin tests github actions to use multiple neo4j database versions
> Adds multiple neo4j versions for e2e tests

- packages/graphql/tests/performance/graphql/connections.graphql
Updates a performance test to make it more representative of a real case
> Update performance test on connection movies with sort

- .changeset/pre.json
> **Note**
> 
Enters the `4.0.0` branch into prerelease mode, which means major bumps will not result in major bumps, but in bumps to the beta tag.
> **Note**
>
> Enter 4.0.0 branch into prerelease mode

- .github/workflows/performance-tests.yml
Only run the performance tests on changes in packages/graphql and packages/cypher-builder
> Trigger performance tests only on changes in packages/graphql and packages/cypher-builder

- examples/subscriptions/apollo_rabbitmq/package.json
- packages/plugins/graphql-plugin-subscriptions-amqp/package.json
- yarn.lock
Supersedes https://github.com/neo4j/graphql/pull/2616 as that PR had a renovate related problem.
> fix: update amqplib dependency

- .changeset/angry-lizards-mate.md
- packages/graphql/src/translate/create-aggregate-where-and-params.ts
- packages/graphql/tests/integration/aggregations/where/edge/string.int.test.ts
- packages/graphql/tests/integration/aggregations/where/node/string.int.test.ts
- packages/graphql/tests/tck/aggregations/where/edge/bigint.test.ts
- packages/graphql/tests/tck/aggregations/where/edge/datetime.test.ts
- packages/graphql/tests/tck/aggregations/where/edge/duration.test.ts
- packages/graphql/tests/tck/aggregations/where/edge/float.test.ts
- packages/graphql/tests/tck/aggregations/where/edge/id.test.ts
- packages/graphql/tests/tck/aggregations/where/edge/int.test.ts
- packages/graphql/tests/tck/aggregations/where/edge/localdatetime.test.ts
- packages/graphql/tests/tck/aggregations/where/edge/localtime.test.ts
- packages/graphql/tests/tck/aggregations/where/edge/string.test.ts
- packages/graphql/tests/tck/aggregations/where/edge/time.test.ts
- packages/graphql/tests/tck/aggregations/where/node/bigint.test.ts
- packages/graphql/tests/tck/aggregations/where/node/datetime.test.ts
- packages/graphql/tests/tck/aggregations/where/node/duration.test.ts
- packages/graphql/tests/tck/aggregations/where/node/float.test.ts
- packages/graphql/tests/tck/aggregations/where/node/id.test.ts
- packages/graphql/tests/tck/aggregations/where/node/int.test.ts
- packages/graphql/tests/tck/aggregations/where/node/localdatetime.test.ts
- packages/graphql/tests/tck/aggregations/where/node/localtime.test.ts
- packages/graphql/tests/tck/aggregations/where/node/string.test.ts
- packages/graphql/tests/tck/aggregations/where/node/time.test.ts
Uses mapDbToProperty on aggregation filtering to fix `@alias` fields
Closes #2656
> Fix db field aggregations filter

- .changeset/tough-mails-buy.md
> **Note**
> 
Gives the auth plugin a major bump following the major upgrade of `jsonwebtoken` in #2622.
> **Note**
>
> **Note**
>
>  
Closes #2686.
> Add major changeset for auth plugin

- .github/workflows/dev.yml
- .github/workflows/reusable-api-library-tests.yml
- .github/workflows/reusable-integration-tests-on-prem-nightly.yml
- .github/workflows/reusable-integration-tests-on-prem.yml
- .github/workflows/reusable-unit-tests.yml
Fixes changes made in https://github.com/neo4j/graphql/pull/2716 due to failure in nightly build run: https://github.com/neo4j/graphql/actions/runs/3907995769.
> fix: nightly build of dev branch

- packages/graphql/tests/performance/graphql/update/update.graphql
> **Note**
> 
Adds a performance test which can be used to verify the impact of #2752.
> **Note**
>
> Add nested update performance test which currently uses apoc.do.when

- .github/workflows/reusable-toolbox-tests.yml
Remove the workaround for the "playwright install connectivity issue" added in https://github.com/neo4j/graphql/pull/2729
> fix: remove playwright workaround

- packages/graphql/src/translate/create-connect-and-params.ts
- packages/graphql/src/translate/create-disconnect-and-params.ts
This PR fixes the last 4 remaining lint errors in the project
> Fix eslint error

- .changeset/fluffy-shoes-cheat.md
- packages/graphql/src/translate/create-aggregate-where-and-params.ts
- packages/graphql/src/translate/where/property-operations/create-comparison-operation.ts
- packages/graphql/tests/integration/aggregations/where/edge/duration.int.test.ts
- packages/graphql/tests/tck/aggregations/where/edge/duration.test.ts
- packages/graphql/tests/tck/aggregations/where/node/duration.test.ts
- packages/graphql/tests/utils/graphql-types.ts
Fixes the cypher generating comparison of duration fields in aggregation
Closes #2697
> Update aggregation operations to properly check durations

- packages/graphql/src/translate/create-aggregate-where-and-params.ts
- packages/graphql/src/translate/where/property-operations/create-comparison-operation.ts
- packages/graphql/src/translate/where/property-operations/create-point-comparison-operation.ts
- packages/graphql/tests/integration/aggregations/where/edge/duration.int.test.ts
Improves code on aggregations
This is a follow-up on https://github.com/neo4j/graphql/pull/2785
> Improve aggregation comparison operations

- .changeset/moody-colts-retire.md
- packages/introspector/src/to-internal-struct.ts
- packages/introspector/src/utils/escape-label.ts
- packages/introspector/tests/integration/graphql/label-injection.test.ts
Fix cases in which a relationship label is a cypher code that may lead to cypher injection through introspection
Complexity: Medium
> Fix cypher injection through introspector relationships

- .github/workflows/docs-teardown.yml
- .github/workflows/ui-stage-teardown.yml
> **Note**
> 
Forgot to add the same headers to the teardown messages in #2828!
> **Note**
>
> Add headers to teardown messages

- docs/rfcs/rfc-010-cypher-builder.md
- packages/graphql/tests/integration/types/datetime.int.test.ts
Initial proposal on how to define a complex pattern (e.g. ()-[]-()) using the cypher builder
> RFC on cypher builder complex patterns

- .changeset/khaki-turkeys-crash.md
- packages/cypher-builder/src/Cypher.ts
- packages/cypher-builder/src/expressions/operations/boolean.test.ts
- packages/cypher-builder/src/expressions/operations/boolean.ts
Adds `Cypher.xor` boolean operation
```typescript
const predicate1 = Cypher.coalesce(new Cypher.Variable());
const predicate2 = Cypher.max(new Cypher.Variable());
const xor = Cypher.xor(predicate1, predicate2);
```
Would result on:
```cypher
(coalesce(var0) XOR max(var1))
```
> XOR operation

- packages/graphql/tests/e2e/federation/entities-basics.e2e.test.ts
- packages/graphql/tests/e2e/federation/quickstart.e2e.test.ts
- packages/graphql/tests/e2e/federation/setup/neo4j.ts
Use env variables for federation e2e tests
Replaces `generateUniqueTypes` with `new UniqueType`
> Use env configured db for federation tests

- .github/workflows/reusable-aura-tests.yml
- packages/graphql/jest.global-setup.js
- packages/graphql/jest.global-teardown.js
- packages/graphql/tests/integration/neo4j.ts
> **Note**
> 
Allows us to disable multi DB for integration tests when running against Aura.
> **Note**
>
> Allow multi DB tests to be disabled by environment variable

- .eslintrc.js
> **Note**
> 
Fixes comma-dangle by removing its necessity from functions.
> **Note**
>
> Fix ESLint config, remove comma-dangle from functions

- packages/apollo-federation-subgraph-compatibility/src/index.ts
- packages/apollo-federation-subgraph-compatibility/src/resolvers.ts
- packages/apollo-federation-subgraph-compatibility/src/server.ts
- packages/apollo-federation-subgraph-compatibility/subgraph.config.js
- packages/apollo-federation-subgraph-compatibility/webpack.config.js
- packages/cypher-builder/src/Cypher.ts
- packages/graphql-toolbox/postcss.config.js
- packages/graphql-toolbox/src/modules/EditorView/docexplorer/FieldDoc.tsx
- packages/graphql/src/classes/Neo4jGraphQL.ts
- packages/graphql/src/translate/batch-create/parser.ts
- packages/graphql/src/translate/create-projection-and-params.ts
- packages/graphql/src/translate/projection/subquery/translate-cypher-directive-projection.ts
- packages/graphql/src/utils/get-neo4j-resolve-tree.test.ts
- packages/graphql/tests/integration/issues/2820.int.test.ts
- packages/graphql/tests/integration/issues/2847.int.test.ts
- packages/graphql/tests/integration/issues/2889.int.test.ts
- packages/graphql/tests/integration/neo4j.ts
- packages/ogm/src/generate.ts
- packages/package-tests/babel/index.js
> **Note**
> 
Fix ESLint `comma-dangle` violations on `dev`.
> **Note**
>
> Fix ESLint `comma-dangle` violations (`dev`)

- .changeset/sixty-snakes-return.md
- .eslintrc.js
- packages/graphql/src/schema/get-obj-field-meta.ts
- packages/graphql/src/translate/where/property-operations/create-property-where.ts
- packages/graphql/src/types.ts
- packages/graphql/tests/integration/directives/coalesce.int.test.ts
- packages/graphql/tests/integration/issues/1761.int.test.ts
- packages/graphql/tests/integration/issues/1781.int.test.ts
- packages/graphql/tests/tck/directives/coalesce.test.ts
> **Note**
> 
Fix `@coalesce` and `@default` for Enum List values, which previously caused an error when starting up the server.
> **Note**
>
> **Note**
>
>  
Closes #1761
> Fix `@coalesce` and `@default` for Enum List values

- packages/graphql/src/translate/create-auth-and-params.test.ts
- packages/graphql/src/translate/create-auth-and-params.ts
- packages/graphql/src/translate/create-connect-and-params.ts
- packages/graphql/src/translate/create-connect-or-create-and-params.ts
- packages/graphql/src/translate/create-create-and-params.ts
- packages/graphql/src/translate/create-delete-and-params.ts
- packages/graphql/src/translate/create-disconnect-and-params.ts
- packages/graphql/src/translate/create-update-and-params.ts
- packages/graphql/src/translate/translate-aggregate.ts
- packages/graphql/src/translate/translate-delete.ts
- packages/graphql/src/translate/translate-top-level-cypher.ts
- packages/graphql/src/translate/translate-top-level-match.ts
> **Note**
> 
Update `createAuthAndParams` to return an object, which will make it easier to work with when adding additional return values.
> **Note**
>
> createAuthAndParams to return object

- packages/graphql/src/translate/batch-create/unwind-create-visitors/UnwindCreateVisitor.ts
- packages/graphql/src/translate/create-auth-and-params.ts
- packages/graphql/src/translate/create-auth-predicates.ts
- packages/graphql/src/translate/create-connect-and-params.ts
- packages/graphql/src/translate/create-connect-or-create-and-params.ts
- packages/graphql/src/translate/create-create-and-params.ts
- packages/graphql/src/translate/create-delete-and-params.ts
- packages/graphql/src/translate/create-disconnect-and-params.ts
- packages/graphql/src/translate/deprecated/auth/create-sub-predicate.ts
- packages/graphql/src/translate/field-aggregations/field-aggregations-auth.ts
> **Note**
> 
Removes `insideDoWhen` and `escapeQuotes` arguments which appear to be completely pointless!
> **Note**
>
> Remove redundant arguments

- .changeset/gentle-colts-relate.md
- docs/modules/ROOT/pages/api-reference/neo4jgraphql.adoc
- packages/graphql/src/classes/Neo4jGraphQL.ts
This PR removes the deprecated skipValidateTypeDefs
Low
> Remove deprecated skipValidateTypeDefs

- .github/workflows/cla-assistant.yml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19c4xH8l4KznjZQ4yQFIZXH5rwv2928%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=NdT0uCL)
> **Note**
> 
The next stage in trialling CLA Assistant, slightly later than planned, is to try their GitHub Action to see if it removes some of the problems we encountered with the hosted version.
> **Note**
>
> Add GHA for CLA Assistant

- .changeset/smart-actors-give.md
- packages/graphql/src/classes/Executor.ts
- packages/graphql/src/schema/resolvers/wrapper.ts
- packages/graphql/src/types/index.ts
- packages/graphql/src/utils/execute.test.ts
- packages/graphql/src/utils/execute.ts
- packages/graphql/tests/utils/builders/context-builder.ts
> **Note**
> 
Added a new `source` object to transaction config, containing source GraphQL query and parameters. These will be emitted in the database query logs, which will aid in debugging from the database logs.
> **Note**
>
> Add source query and params to driver transaction config

- docs/modules/ROOT/pages/ogm/examples/custom-resolvers.adoc
Based on internal Trello card.
> **Note**
>
> docs: OGM custom resolver util functions

- docs/modules/ROOT/pages/guides/apollo-federation.adoc
> docs: Apollo federation guide additions

- .github/workflows/reusable-toolbox-tests.yml
> **Note**
> 
Build the introspector, a referenced project of the Toolbox, as part of the Toolbox GHA test suite to prevent the occasionally occurring reference error.
> **Note**
>
> boyscouting: Toolbox E2E test GHA, build introspector

- .changeset/weak-cars-obey.md
- packages/graphql-toolbox/src/modules/AppSettings/AppSettings.tsx
- packages/graphql-toolbox/tests/pages/ApplicationSettings.ts
- packages/graphql-toolbox/tests/settings.test.ts
> **Note**
> 
Making sure the copyright information displayed in the Toolbox settings is up to date. Check with a e2e test.
> **Note**
>
> boyscouting: Toolbox, copyright information with current year

- .github/workflows/reusable-api-library-tests.yml
- .github/workflows/reusable-integration-tests-on-prem.yml
- renovate.json
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1Ud7tYg6E0GFynwJ0xymn99Io4XTBRI%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=nkmMbKo)
Reverts neo4j/graphql#3361
> Revert "chore(deps): update neo4j docker tag to v4.4"

- .changeset/violet-mugs-hammer.md
- packages/graphql/src/graphql/directives/index.ts
- packages/graphql/src/graphql/directives/selectable.ts
- packages/graphql/src/schema/create-connection-fields.ts
- packages/graphql/src/schema/create-relationship-fields/create-relationship-fields.ts
- packages/graphql/src/schema/get-obj-field-meta.ts
- packages/graphql/src/schema/make-augmented-schema.ts
- packages/graphql/src/schema/resolvers/subscriptions/where.test.ts
- packages/graphql/src/schema/to-compose.ts
- packages/graphql/src/translate/create-auth-and-params.test.ts
- packages/graphql/src/translate/create-connect-and-params.test.ts
- packages/graphql/src/translate/create-create-and-params.test.ts
- packages/graphql/src/translate/create-disconnect-and-params.test.ts
- packages/graphql/src/translate/create-projection-and-params.test.ts
- packages/graphql/src/translate/create-update-and-params.test.ts
- packages/graphql/src/translate/projection/elements/create-relationship-property-element.test.ts
- packages/graphql/src/types/index.ts
- packages/graphql/tests/schema/directives/selectable.test.ts
- packages/graphql/tests/utils/builders/relation-field-builder.ts
Adds `@selectable` directive defined in #3263 
This directive has the following options:
* onRead
* onAggregate
Setting these values will disable the generation of the GraphQL fields for responses or aggregations
Complexity: Medium
> Selectable directive

- docs/modules/ROOT/pages/type-definitions/types.adoc
This page moved to another section in the Cypher manual, thus the 404 error.
> Broken link fix

- .changeset/nice-fans-complain.md
This PR adds the changeset for #3404
> Add changeset for settable directives

- docs/modules/ROOT/pages/introspector.adoc
> **Note**
> 
Add missing import statement to introspector getting started page.
> **Note**
>
Low
> docs: add missing import statement to introspector getting started page

- .changeset/odd-plums-jump.md
- packages/graphql-toolbox/src/index.css
- packages/graphql-toolbox/src/modules/EditorView/EditorView.tsx
- packages/graphql-toolbox/src/modules/EditorView/grid/Grid.tsx
- packages/graphql-toolbox/src/modules/HelpDrawer/DocExplorerComponent.tsx
- packages/graphql-toolbox/src/modules/HelpDrawer/Keybindings.tsx
- packages/graphql-toolbox/src/modules/HelpDrawer/Resources.tsx
- packages/graphql-toolbox/src/modules/Login/Login.tsx
- packages/graphql-toolbox/src/modules/SchemaView/SchemaEditor.tsx
> **Note**
> 
- Clean up `src/index.css` file
- Add missing copyright headers
- Removed unused key bindings entries
- Shortened the warning tooltip message on the Login window
> **Note**
>
Low
> feat: Toolbox - clean-up after code mirror v6 integration

- .changeset/strange-clocks-kneel.md
- packages/graphql-toolbox/src/index.css
- packages/graphql-toolbox/src/modules/AppSettings/AppSettings.tsx
- packages/graphql-toolbox/src/modules/HelpDrawer/HelpDrawer.tsx
> **Note**
> 
Fixes:
- Right-hand siders, introduce scroll on y-axis
- QueryExplorer component and Docs GraphiQL v2 component use Nunito Sans font-family 
> **Note**
>
Low
> fix: Toolbox - right-hand sider and font-family for components

- packages/graphql/src/schema/create-relationship-fields/create-relationship-fields.ts
- packages/graphql/src/schema/create-relationship-fields/create-relationship-interface-fields.ts
- packages/graphql/src/schema/create-relationship-fields/create-relationship-union-fields.ts
This PR cleans up some of the relationship schema field generation code to make it easier to understand what is intended.
Low
> Refactor relationship schema generation code

- .changeset/hip-fireants-kiss.md
- packages/graphql-toolbox/README.md
> **Note**
> 
Bump the Toolbox to v2.0.0
> feat: Toolbox - major version bump

- packages/graphql/tests/integration/issues/505.int.test.ts
> **Note**
> 
> **Note**
>
Complexity:
> **Note**
>
>  
Closes 
> Fix missed `@auth` directive

- .changeset/violet-parrots-grow.md
This PR contains the changeset to encompass the pull requests for authorization.
* #3101 added authorization and authentication for query and mutation operations
* #3565 added authorization for subscription operations
> changeset for authorization

- packages/graphql/src/schema/make-augmented-schema.ts
- packages/graphql/src/schema/resolvers/subscriptions/subscribe.ts
- packages/graphql/src/schema/resolvers/subscriptions/where/filters/filter-by-authorization-rules.ts
- packages/graphql/tests/e2e/subscriptions/authorization/filter/create-relationship.e2e.test.ts
- packages/graphql/tests/e2e/subscriptions/authorization/filter/create.e2e.test.ts
- packages/graphql/tests/e2e/subscriptions/authorization/filter/delete-relationship.e2e.test.ts
- packages/graphql/tests/e2e/subscriptions/authorization/filter/delete.e2e.test.ts
- packages/graphql/tests/e2e/subscriptions/authorization/filter/update.e2e.test.ts
Should fix the remaining handful of broken tests on `4.0.0.`
> Fix broken tests on `4.0.0`

- .changeset/stale-lamps-doubt.md
- packages/ogm/src/utils/filter-document.ts
- packages/ogm/tests/integration/ogm.int.test.ts
Ignore `@authentication`, `@authorization` and `subscriptionsAuthorization` directives in the OGM
Closes #3594
> Ignore `@authentication`, `@authorization` and `subscriptionsAuthorization` directives in the OGM

- packages/graphql/tests/integration/issues/2548.int.test.ts
Adds a test satisfying #2548.
Closes #2548
> Adds a test satisfying #2548

- packages/graphql/tests/schema/issues/3439.test.ts
- packages/ogm/src/classes/Model.ts
Strongly type `context` field in OGM.
> Strongly type `context` field in OGM

- docs/modules/ROOT/pages/reference/api-reference/neo4jgraphql.adoc
- packages/graphql/src/classes/Neo4jGraphQL.test.ts
- packages/graphql/src/classes/Neo4jGraphQL.ts
Remove `neo4jValidateGraphQLDocument`
> Remove `neo4jValidateGraphQLDocument`

- packages/introspector/README.md
> **Note**
> 
A `readonly` variable is defined yet not needed in that example.
> **Note**
>
> **Note**
>
>  
Closes https://github.com/neo4j/graphql/issues/3732
> introspector: remove readonly in README

- packages/graphql/src/translate/queryAST/ast/filters/aggregation/CountFilter.ts
- packages/graphql/src/translate/translate-read.ts
- packages/graphql/tests/tck/aggregations/where/composite.test.ts
Add some tck tests for aggregation filters
> Add aggregation filters tests for logical filters

- packages/graphql/src/translate/queryAST/ast/filters/RelationshipFilter.ts
- packages/graphql/src/translate/queryAST/factory/FilterFactory.ts
> Null operator on relationship

- packages/graphql/src/translate/queryAST/ast/filters/aggregation/AggregationFilter.ts
- packages/graphql/src/translate/queryAST/ast/filters/aggregation/CountFilter.ts
- packages/graphql/src/translate/queryAST/factory/FilterFactory.ts
Fix remaining aggregation tck tests:
```
Test Suites: 75 failed, 162 passed, 237 total
Tests:       231 failed, 1028 passed, 1259 total
```
> Aggregation logical filters

- packages/graphql/src/translate/create-aggregate-where-and-params.ts
- packages/graphql/tests/integration/issues/3765.int.test.ts
- packages/graphql/tests/tck/issues/3765.test.ts
The problem appears to be caused by a couple of missing logical operators for default values
closes #3765
> Fix default logical operators in aggregation filters

- packages/graphql/src/translate/queryAST/ast/operations/ConnectionReadOperation.ts
- packages/graphql/src/translate/queryAST/factory/FieldFactory.ts
- packages/graphql/tests/tck/connections/relationship-properties.test.ts
Fix nested connections, fixing `relationship-properties`
A minor change in the resulting Cypher required some tck tests to be updated
> Fix nested connections

- packages/graphql/src/classes/authorization/Neo4jGraphQLAuthorization.ts
- packages/graphql/src/types/index.ts
These were obviously left behind from the authorization refactor - tidying up.
> Remove references to global authentication

- packages/graphql/src/translate/queryAST/ast/filters/ConnectionFilter.ts
- packages/graphql/src/translate/queryAST/ast/filters/Filter.ts
- packages/graphql/src/translate/queryAST/ast/filters/RelationshipFilter.ts
- packages/graphql/src/translate/queryAST/ast/filters/aggregation/AggregationFilter.ts
- packages/graphql/tests/tck/issues/2708.test.ts
Fix tests on 2708 in new translation layer
```
Test Suites: 59 failed, 179 passed, 238 total
Tests:       172 failed, 1105 passed, 1277 total
```
> fix 2708 tests in new translation layer

- packages/graphql/src/translate/queryAST/ast/filters/ConnectionFilter.ts
Fix several cases for connections
> Fix translation 2803

- packages/graphql/src/translate/queryAST/ast/QueryASTNode.ts
- packages/graphql/src/translate/queryAST/ast/fields/Field.ts
- packages/graphql/src/translate/queryAST/ast/fields/OperationField.ts
- packages/graphql/src/translate/queryAST/ast/fields/attribute-fields/CypherAttributeField.ts
- packages/graphql/src/translate/queryAST/ast/filters/ConnectionFilter.ts
- packages/graphql/src/translate/queryAST/ast/filters/Filter.ts
- packages/graphql/src/translate/queryAST/ast/filters/LogicalFilter.ts
- packages/graphql/src/translate/queryAST/ast/filters/RelationshipFilter.ts
- packages/graphql/src/translate/queryAST/ast/filters/aggregation/AggregationFilter.ts
- packages/graphql/src/translate/queryAST/ast/filters/authorization-filters/AuthRelationshipFilter.ts
- packages/graphql/src/translate/queryAST/ast/filters/authorization-filters/AuthorizationFilters.ts
- packages/graphql/src/translate/queryAST/ast/filters/authorization-filters/AuthorizationRuleFilter.ts
- packages/graphql/src/translate/queryAST/ast/operations/AggregationOperation.ts
- packages/graphql/src/translate/queryAST/ast/operations/ConnectionReadOperation.ts
- packages/graphql/src/translate/queryAST/ast/operations/ReadOperation.ts
Pass the context to `getSubqueries` instead of just a node
> Use queryASTContext in getSubquery

- packages/graphql/src/schema-model/parser/annotations-parser/default-annotation.ts
Schema model fix to ensure we do not exclude default values which are themselves falsy.
Low
> Ensure default values which are falsy are not excluded

- packages/graphql/src/schema-model/annotation/Annotation.ts
- packages/graphql/src/schema-model/annotation/RelayIDAnnotation.ts
Adds the relayId directive annotation to the schema model.
Low
> Add relayId annotation to schema model

- packages/graphql/src/schema-model/entity/model-adapters/InterfaceEntityAdapter.ts
- packages/graphql/src/translate/queryAST/ast/operations/ConnectionReadOperation.ts
- packages/graphql/src/translate/queryAST/ast/operations/interfaces/InterfaceConnectionPartial.ts
- packages/graphql/src/translate/queryAST/ast/operations/interfaces/InterfaceConnectionReadOperation.ts
- packages/graphql/src/translate/queryAST/factory/FieldFactory.ts
- packages/graphql/src/translate/queryAST/factory/FilterFactory.ts
- packages/graphql/src/translate/queryAST/factory/OperationFactory.ts
- packages/graphql/src/translate/queryAST/factory/SortAndPaginationFactory.ts
- packages/graphql/src/translate/queryAST/utils/is-concreate-entity.ts
- packages/graphql/src/translate/translate-read.ts
- packages/graphql/tests/tck/directives/authorization/arguments/where/where.test.ts
- packages/graphql/tests/tck/issues/1685.test.ts
This approach uses 2 classes, splitting the connectionsOperation into the components required for interfaces.
The result is not very readable, and more work should be done to reduce code duplication and make the interfaces solution more reusable
```
Test Suites: 44 failed, 195 passed, 239 total
Tests:       107 failed, 1174 passed, 1281 total
```
> Interfaces translation layer

- packages/graphql/src/translate/queryAST/ast/filters/ConnectionFilter.ts
- packages/graphql/src/translate/queryAST/factory/FilterFactory.ts
- packages/graphql/src/translate/queryAST/factory/OperationFactory.ts
- packages/graphql/src/translate/queryAST/utils/get-concrete-entities.ts
- packages/graphql/tests/tck/issues/3923.test.ts
This PR fixes nested connection filters on interfaces, including new bug #3923
This takes the approach of creating multiple connectionFilters
> Fix #3924 on new translation layer

- .github/workflows/cla-assistant.yml
This is a long delayed step in our trial of a new CLA tool - testing the GHA edition of CLA Assistant. If when merged, this appears to be working correctly, the current hosted version will be disabled, and I can report back to the working group.
> Setup CLA Assistant GHA

- packages/graphql/src/classes/Node.ts
- packages/graphql/src/classes/NodeDirective.test.ts
- packages/graphql/src/classes/NodeDirective.ts
- packages/graphql/src/schema-model/entity/model-adapters/ConcreteEntityAdapter.ts
- packages/graphql/src/schema-model/utils/map-labels-with-context.ts
- packages/graphql/src/translate/queryAST/ast/QueryAST.ts
- packages/graphql/src/translate/queryAST/ast/QueryASTContext.ts
- packages/graphql/src/translate/queryAST/ast/fields/OperationField.ts
- packages/graphql/src/translate/queryAST/ast/operations/AggregationOperation.ts
- packages/graphql/src/translate/queryAST/ast/operations/ConnectionReadOperation.ts
- packages/graphql/src/translate/queryAST/ast/operations/ReadOperation.ts
- packages/graphql/src/translate/queryAST/ast/operations/interfaces/InterfaceConnectionPartial.ts
- packages/graphql/src/translate/queryAST/ast/operations/interfaces/InterfaceConnectionReadOperation.ts
- packages/graphql/src/translate/queryAST/ast/operations/operations.ts
- packages/graphql/src/translate/queryAST/utils/create-cypher-subquery.ts
- packages/graphql/src/translate/queryAST/utils/create-node-from-entity.ts
- packages/graphql/src/translate/translate-read.ts
- packages/graphql/tests/tck/issues/1249.test.ts
Support for dynamic labels
This PR fixes:
- 'Label in Node directive Select Movie with label Film',
- 'https://github.com/neo4j/graphql/issues/1249 should contain the cypherParams that are passed via the context'
It also removes parentNode from the transpile contract, and shares code between the old NodeDirective and the new Schema Model Concrete Entity.
> Support for dynamic labels

- packages/graphql/src/translate/queryAST/ast/operations/interfaces/InterfaceReadOperation.ts
- packages/graphql/src/translate/queryAST/factory/FieldFactory.ts
- packages/graphql/src/translate/queryAST/factory/FilterFactory.ts
- packages/graphql/src/translate/queryAST/factory/OperationFactory.ts
- packages/graphql/src/translate/queryAST/factory/SortAndPaginationFactory.ts
- packages/graphql/src/translate/queryAST/utils/is-composite-entity.ts
- packages/graphql/src/translate/queryAST/utils/is-concrete-entity.ts
- packages/graphql/src/translate/queryAST/utils/is-interface-entity.ts
- packages/graphql/src/translate/queryAST/utils/is-union-entity.ts
- packages/graphql/tests/tck/directives/interface-relationships/read.test.ts
- packages/graphql/tests/tck/directives/node/node-label-interface.test.ts
- packages/graphql/tests/tck/directives/node/node-label-union.test.ts
- packages/graphql/tests/tck/union.test.ts
'Cypher Union Read Unions simple',
'Cypher Union Read Unions with filter and limit',
'Cypher Union Read Unions with missing types',
'Interface Relationships Filter overriding using onType',
'Node directive with unions Read Unions',
'https://github.com/neo4j/graphql/issues/1779 EXISTS should not be within return clause'
]
Regressions in branch B:  []
> Unify Abstract operation factory logic

- packages/graphql/src/translate/queryAST/ast/filters/authorization-filters/AuthorizationFilters.ts
- packages/graphql/src/translate/queryAST/ast/operations/ConnectionReadOperation.ts
- packages/graphql/src/translate/queryAST/ast/operations/ReadOperation.ts
- packages/graphql/src/translate/queryAST/ast/operations/interfaces/InterfaceConnectionPartial.ts
- packages/graphql/src/translate/queryAST/ast/operations/interfaces/InterfaceReadPartial.ts
- packages/graphql/src/translate/queryAST/factory/AuthorizationFactory.ts
- packages/graphql/src/translate/queryAST/factory/OperationFactory.ts
- packages/graphql/tests/tck/directives/authorization/arguments/allow/allow.test.ts
- packages/graphql/tests/tck/directives/authorization/arguments/roles/roles.test.ts
- packages/graphql/tests/tck/rfcs/rfc-022.test.ts
Fix auth on attributes
```
'Cypher Auth Allow > Read Node & Protected Field',
'Cypher Auth Allow > Read Relationship & Protected Field',
'Cypher Auth Roles > Read Node & Cypher Field',
'Cypher Auth Roles > Read Node & Field',
'tck/rfs/022 subquery projection > With auth > Nested query'
]
Regressions in branch B:  []
```
> Fix attribute auth

- .eslintrc.js
- packages/graphql/src/schema-model/annotation/CustomResolverAnnotation.ts
- packages/graphql/src/schema-model/attribute/AttributeType.ts
- packages/graphql/src/schema-model/entity/model-adapters/ConcreteEntityAdapter.ts
- packages/graphql/src/schema-model/entity/model-adapters/InterfaceEntityAdapter.ts
- packages/graphql/src/schema-model/generate-model.ts
- packages/graphql/src/schema-model/parser/annotations-parser/custom-resolver-annotation.ts
- packages/graphql/src/schema-model/parser/definition-collection.ts
- packages/graphql/src/schema-model/parser/parse-attribute.ts
- packages/graphql/src/schema/get-custom-resolver-meta.ts
This PR includes changes required in schema model for the translation layer:
* Update .eslintrc with `no-unused-vars` rule
* Update customResolverAnnotation to generate resolveTree
* Add some utility functions to some adapters needed in translation layer
> Changes in schema model for new translation layer

- packages/graphql/package.json
- packages/graphql/src/translate/queryAST/ast/fields/attribute-fields/CypherUnionAttributePartial.ts
- packages/graphql/tests/tck/issues/1848.test.ts
- yarn.lock
Fix tck tests `1848`:
```
Test Suites: 4 failed, 237 passed, 241 total
Tests:       9 failed, 1276 passed, 1285 total
```
> Fix labels filter on cypher directive with unions

- packages/graphql/src/translate/queryAST/ast/filters/RelationshipFilter.ts
```
Test Suites: 2 failed, 239 passed, 241 total
Tests:       5 failed, 1280 passed, 1285 total
```
> Fix some relationship filters

- packages/graphql/src/translate/queryAST/ast/fields/attribute-fields/CypherAttributeField.ts
- packages/graphql/src/translate/queryAST/ast/fields/attribute-fields/CypherUnionAttributeField.ts
- packages/graphql/src/translate/queryAST/ast/sort/CypherPropertySort.ts
- packages/graphql/src/translate/queryAST/utils/create-cypher-subquery.ts
- packages/graphql/tests/tck/directives/cypher.test.ts
> Fix cypher with union tck tests

- packages/graphql/src/translate/queryAST/ast/operations/ReadOperation.ts
- packages/graphql/src/translate/queryAST/factory/OperationFactory.ts
- packages/graphql/tests/integration/issues/2766.int.test.ts
- packages/graphql/tests/tck/issues/2766.test.ts
```
Test Suites: 12 failed, 296 passed, 308 total
Tests:       24 failed, 2 skipped, 1634 passed, 1660 total
```
> Fix aggregation and nested queries tests

- packages/graphql/src/translate/queryAST/ast/fields/attribute-fields/CypherAttributeField.ts
- packages/graphql/src/translate/queryAST/ast/fields/attribute-fields/CypherUnionAttributeField.ts
Fixes failing customResolver.int.ts
> Remove scope errors

- .changeset/short-pears-refuse.md
- packages/graphql/src/schema-model/attribute/AttributeType.ts
- packages/graphql/tests/schema/issues/3905.test.ts
- packages/graphql/tests/tck/issues/3905.test.ts
Although lists of lists were switched to a warning in validation, this step in the schema model was causing an error regardless.
Closes #3905
> Remove list of lists validation in schema model

- .changeset/rotten-dolls-clean.md
- packages/graphql/src/schema-model/attribute/AttributeType.ts
- packages/graphql/src/schema-model/parser/parse-attribute.ts
- packages/graphql/tests/tck/issues/4001.test.ts
Fix for issue #4001
#4001 
Closes 
> parse to UnknownType in case of user defined types

- packages/graphql/src/translate/queryAST/factory/FieldFactory.ts
- packages/graphql/src/translate/queryAST/factory/OperationFactory.ts
- packages/graphql/src/translate/translate-read.ts
- packages/graphql/tests/tck/fragments.test.ts
- packages/graphql/tests/tck/issues/583.test.ts
> Fix top level interface with fragments

- packages/graphql/src/translate/queryAST/ast/operations/ConnectionReadOperation.ts
- packages/graphql/src/translate/queryAST/ast/operations/interfaces/InterfaceConnectionReadOperation.ts
- packages/graphql/src/translate/queryAST/factory/OperationFactory.ts
- packages/graphql/src/translate/queryAST/factory/SortAndPaginationFactory.ts
```
'Connections -> Interfaces > Projecting node and relationship properties with pagination',
'Connections -> Unions > Projecting node and relationship properties with pagination'
]
Regressions in branch B:  []
```
> Fix connection sort

- packages/graphql/tests/integration/issues/4015.int.test.ts
- packages/graphql/tests/tck/issues/4015.test.ts
> add tests for issue #4015

- .changeset/famous-countries-reflect.md
This PR includes the minor changeset following the translation-layer merge.
> add changeset for the QueryAST implementation

- .changeset/lemon-elephants-camp.md
- packages/graphql/src/translate/queryAST/ast/operations/ReadOperation.ts
- packages/graphql/src/translate/queryAST/factory/AuthFilterFactory.ts
- packages/graphql/tests/integration/issues/4110.int.test.ts
- packages/graphql/tests/tck/directives/authorization/arguments/allow/allow.test.ts
- packages/graphql/tests/tck/directives/authorization/arguments/roles-where.test.ts
- packages/graphql/tests/tck/directives/authorization/arguments/where/interface-relationships/implementation-where.test.ts
- packages/graphql/tests/tck/directives/authorization/arguments/where/where.test.ts
- packages/graphql/tests/tck/issues/2396.test.ts
- packages/graphql/tests/tck/issues/4077.test.ts
- packages/graphql/tests/tck/issues/4110.test.ts
- packages/graphql/tests/tck/issues/505.test.ts
- packages/graphql/tests/tck/issues/601.test.ts
- packages/graphql/tests/tck/rfcs/rfc-022.test.ts
Fix authentication filters with subqueries
> Fix authentication subqueries and filters #4110

- .changeset/giant-tools-look.md
- packages/graphql/src/translate/queryAST/ast/operations/AggregationOperation.ts
- packages/graphql/tests/integration/aggregations/field-level/where/field-aggregation-where.int.test.ts
- packages/graphql/tests/integration/issues/2548.int.test.ts
- packages/graphql/tests/integration/issues/4110.int.test.ts
- packages/graphql/tests/integration/issues/4115.int.test.ts
- packages/graphql/tests/tck/issues/4115.test.ts
- packages/graphql/tests/tck/issues/4116.test.ts
Fix nested aggregation filters #4115 & #4116
> Fix nested aggregation filters #4115

- .changeset/large-bags-refuse.md
- packages/graphql-toolbox/src/modules/SchemaView/Favorites/DragHandle.tsx
- packages/graphql-toolbox/src/modules/SchemaView/Favorites/FavoriteEntry.tsx
- packages/graphql-toolbox/src/modules/SchemaView/SchemaEditor.tsx
This PR addresses the broken e2e tests on the GraphQL Toolbox.
Low
> Fix GraphQL Toolbox tests

- .changeset/config.json
- package.json
- yarn.lock
> Fix Yarn workspace

- packages/graphql/tests/integration/issues/4196.int.test.ts
This PR adds a regression test for the issue reported in #4196  where sorting was incorrect on a previous database version.
Low
> Add regression test for issue 4196

- .changeset/sharp-pugs-doubt.md
- packages/graphql/src/classes/Neo4jGraphQL.ts
This warning was accidentally left in.
> Remove Federation warning

- .changeset/lovely-items-vanish.md
- packages/graphql/src/translate/create-create-and-params.ts
- packages/graphql/tests/integration/issues/4223.int.test.ts
- packages/graphql/tests/tck/directives/authorization/arguments/bind/interface-relationships/implementation-bind.test.ts
- packages/graphql/tests/tck/directives/authorization/arguments/roles-where.test.ts
- packages/graphql/tests/tck/issues/3901.test.ts
- packages/graphql/tests/tck/issues/4118.test.ts
- packages/graphql/tests/tck/issues/4223.test.ts
- packages/graphql/tests/tck/operations/batch/batch-create-auth.test.ts
This PR goes further to construct the authorization variables prefix and includes every (hopefully) possible index at this point. This is a temporary solution to fix the user issue, however we should really migrate create to the new translation layer to eradicate this little monster.
Closes #4223 
> Fix authorization variable prefix

- packages/graphql/package.json
- packages/graphql/src/schema-model/attribute/model-adapters/AttributeAdapter.ts
- packages/graphql/src/schema-model/entity/model-adapters/ConcreteEntityOperations.ts
- packages/graphql/src/schema/resolvers/query/aggregate.ts
- packages/graphql/src/translate/queryAST/ast/QueryAST.ts
- packages/graphql/src/translate/queryAST/ast/fields/aggregation-fields/AggregationAttributeField.ts
- packages/graphql/src/translate/queryAST/ast/fields/aggregation-fields/AggregationField.ts
- packages/graphql/src/translate/queryAST/ast/fields/aggregation-fields/CountField.ts
- packages/graphql/src/translate/queryAST/ast/operations/AggregationOperation.ts
- packages/graphql/src/translate/queryAST/factory/AuthorizationFactory.ts
- packages/graphql/src/translate/queryAST/factory/FieldFactory.ts
- packages/graphql/src/translate/queryAST/factory/OperationFactory.ts
- packages/graphql/src/translate/translate-aggregate.ts
- packages/graphql/src/translate/translate-read.ts
- packages/graphql/src/utils/utils.ts
- packages/graphql/tests/integration/aggregations/top-level/authorization.int.test.ts
- packages/graphql/tests/integration/aggregations/top-level/string.int.test.ts
- packages/graphql/tests/tck/aggregations/alias-directive.test.ts
- packages/graphql/tests/tck/aggregations/alias.test.ts
- packages/graphql/tests/tck/aggregations/auth.test.ts
- packages/graphql/tests/tck/aggregations/count.test.ts
- packages/graphql/tests/tck/aggregations/field-level-aggregations/field-level-aggregations-alias.test.ts
- packages/graphql/tests/tck/aggregations/field-level-aggregations/field-level-aggregations-labels.test.ts
- packages/graphql/tests/tck/aggregations/field-level-aggregations/field-level-aggregations.test.ts
- packages/graphql/tests/tck/aggregations/int.test.ts
- packages/graphql/tests/tck/aggregations/label.test.ts
- packages/graphql/tests/tck/aggregations/localdatetime.test.ts
- packages/graphql/tests/tck/aggregations/many.test.ts
- packages/graphql/tests/tck/aggregations/string.test.ts
- yarn.lock
Moves top level aggregation translation to use QueryAST in preparation of interface aggregation
> Top level aggregations refactor

- packages/graphql/tests/integration/types/bigint.int.test.ts
This PR adds the usage of UniqueType for the bigint integration tests
Low
> Test: use UniqueType in bigint tests

- .changeset/violet-needles-peel.md
- packages/graphql/src/translate/queryAST/factory/FilterFactory.ts
- packages/graphql/src/translate/queryAST/factory/OperationFactory.ts
- packages/graphql/tests/integration/connections/interfaces.int.test.ts
- packages/graphql/tests/integration/issues/4287.int.test.ts
- packages/graphql/tests/tck/connections/interfaces.test.ts
- packages/graphql/tests/tck/directives/interface-relationships/read.test.ts
- packages/graphql/tests/tck/issues/4287.test.ts
Fix logical operators on interface connection filtering
> Fix #4287: Logical operators on connection filtering with interfaces

- packages/graphql/src/classes/Executor.ts
Fix query printing in query logs
> Fix query printing in query logs

- .changeset/unlucky-forks-pretend.md
- packages/graphql/src/translate/queryAST/ast/operations/ReadOperation.ts
- packages/graphql/tests/integration/issues/4477.int.test.ts
- packages/graphql/tests/tck/issues/4477.test.ts
Filtering wasn't working properly on nested read operations, so this PR adds that in.
Low
There are several changes in `ReadOperation` but it is mainly code re-organisation to aid future refactoring
Closes #4477
> Fix: 4477 filtering by count on an aggregate

- .changeset/fresh-toys-impress.md
- packages/graphql/src/schema-model/library-directives.ts
- packages/graphql/src/schema/make-augmented-schema.ts
- packages/graphql/src/schema/make-augmented-schema/user-defined-directives.ts
- packages/graphql/tests/schema/experimental-schema/inheritance.test.ts
- packages/graphql/tests/schema/inheritance.test.ts
Fixes the missing takeover of custom directives for interfaces
Complexity: low
closes #4566
> Fixes the missing takeover of custom directives for interfaces
